///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace EH.PCPS.TestAutomation.NXA_HARTCommDTM.V119580.ChangeDtmAddress.GUI.ApplicationArea.MainView
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the ChangeDTMAddressMainViewRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    [RepositoryFolder("f3873453-29e4-4a85-8e18-2291ad47488d")]
    public partial class ChangeDTMAddressMainViewRepository : RepoGenBaseFolder
    {
        static ChangeDTMAddressMainViewRepository instance = new ChangeDTMAddressMainViewRepository();
        RepoItemInfo _changeInfo;
        RepoItemInfo _refreshInfo;
        RepoItemInfo _changedeviceaddresscomboboxInfo;
        RepoItemInfo _comboboxlistitemInfo;
        RepoItemInfo _comboboxlistInfo;
        RepoItemInfo _treeitemdevicelistInfo;

        /// <summary>
        /// Gets the singleton class instance representing the ChangeDTMAddressMainViewRepository element repository.
        /// </summary>
        [RepositoryFolder("f3873453-29e4-4a85-8e18-2291ad47488d")]
        public static ChangeDTMAddressMainViewRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public ChangeDTMAddressMainViewRepository() 
            : base("ChangeDTMAddressMainViewRepository", "/", null, 0, false, "f3873453-29e4-4a85-8e18-2291ad47488d", ".\\RepositoryImages\\ChangeDTMAddressMainViewRepositoryf3873453.rximgres")
        {
            _changeInfo = new RepoItemInfo(this, "Change", "/?/form//container[@controlname='ContainerForm']/element[@controlname='changeButton']/button[@accessiblename='Change']", 30000, null, "81ac584e-1b2e-4770-8f3c-4fd238c77d80");
            _refreshInfo = new RepoItemInfo(this, "Refresh", "/?/form//container[@controlname='ContainerForm']/element[@controlname='refreshButton']/button[@accessiblename='Refresh']", 30000, null, "9d10d441-05d7-4602-9b10-1e1a9edea08c");
            _changedeviceaddresscomboboxInfo = new RepoItemInfo(this, "ChangeDeviceAddressComboBox", "/?/form/?/?/container[@controlname='GUITransparentProxy']/?/?/element[@controlname='changeDeviceAddressComboBox']", 30000, null, "16510ff6-9578-40bc-be65-d8a427bfec5c");
            _comboboxlistitemInfo = new RepoItemInfo(this, "comboBoxListItem", "/form/element/list/listitem", 30000, null, "148d0623-a03e-4771-be0d-d9fee8496f67");
            _comboboxlistInfo = new RepoItemInfo(this, "comboBoxList", "/form/element/list", 30000, null, "8758146b-1ba7-4971-913a-71ac98f572aa");
            _treeitemdevicelistInfo = new RepoItemInfo(this, "treeItemDeviceList", "/?/form/?/?/container[@controlname='GUITransparentProxy']/?/?/element[@controlname='deviceListControl']/tree[@accessiblename='deviceListControl']/container[2]/treeitem", 30000, null, "3abfd062-4e28-449f-8f1f-8b1ffd2974f3");
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("f3873453-29e4-4a85-8e18-2291ad47488d")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Change item.
        /// </summary>
        [RepositoryItem("81ac584e-1b2e-4770-8f3c-4fd238c77d80")]
        public virtual Ranorex.Button Change
        {
            get
            {
                 return _changeInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The Change item info.
        /// </summary>
        [RepositoryItemInfo("81ac584e-1b2e-4770-8f3c-4fd238c77d80")]
        public virtual RepoItemInfo ChangeInfo
        {
            get
            {
                return _changeInfo;
            }
        }

        /// <summary>
        /// The Refresh item.
        /// </summary>
        [RepositoryItem("9d10d441-05d7-4602-9b10-1e1a9edea08c")]
        public virtual Ranorex.Button Refresh
        {
            get
            {
                 return _refreshInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The Refresh item info.
        /// </summary>
        [RepositoryItemInfo("9d10d441-05d7-4602-9b10-1e1a9edea08c")]
        public virtual RepoItemInfo RefreshInfo
        {
            get
            {
                return _refreshInfo;
            }
        }

        /// <summary>
        /// The ChangeDeviceAddressComboBox item.
        /// </summary>
        [RepositoryItem("16510ff6-9578-40bc-be65-d8a427bfec5c")]
        public virtual Ranorex.Unknown ChangeDeviceAddressComboBox
        {
            get
            {
                 return _changedeviceaddresscomboboxInfo.CreateAdapter<Ranorex.Unknown>(true);
            }
        }

        /// <summary>
        /// The ChangeDeviceAddressComboBox item info.
        /// </summary>
        [RepositoryItemInfo("16510ff6-9578-40bc-be65-d8a427bfec5c")]
        public virtual RepoItemInfo ChangeDeviceAddressComboBoxInfo
        {
            get
            {
                return _changedeviceaddresscomboboxInfo;
            }
        }

        /// <summary>
        /// The comboBoxListItem item.
        /// </summary>
        [RepositoryItem("148d0623-a03e-4771-be0d-d9fee8496f67")]
        public virtual Ranorex.ListItem comboBoxListItem
        {
            get
            {
                 return _comboboxlistitemInfo.CreateAdapter<Ranorex.ListItem>(true);
            }
        }

        /// <summary>
        /// The comboBoxListItem item info.
        /// </summary>
        [RepositoryItemInfo("148d0623-a03e-4771-be0d-d9fee8496f67")]
        public virtual RepoItemInfo comboBoxListItemInfo
        {
            get
            {
                return _comboboxlistitemInfo;
            }
        }

        /// <summary>
        /// The comboBoxList item.
        /// </summary>
        [RepositoryItem("8758146b-1ba7-4971-913a-71ac98f572aa")]
        public virtual Ranorex.List comboBoxList
        {
            get
            {
                 return _comboboxlistInfo.CreateAdapter<Ranorex.List>(true);
            }
        }

        /// <summary>
        /// The comboBoxList item info.
        /// </summary>
        [RepositoryItemInfo("8758146b-1ba7-4971-913a-71ac98f572aa")]
        public virtual RepoItemInfo comboBoxListInfo
        {
            get
            {
                return _comboboxlistInfo;
            }
        }

        /// <summary>
        /// The treeItemDeviceList item.
        /// </summary>
        [RepositoryItem("3abfd062-4e28-449f-8f1f-8b1ffd2974f3")]
        public virtual Ranorex.TreeItem treeItemDeviceList
        {
            get
            {
                 return _treeitemdevicelistInfo.CreateAdapter<Ranorex.TreeItem>(true);
            }
        }

        /// <summary>
        /// The treeItemDeviceList item info.
        /// </summary>
        [RepositoryItemInfo("3abfd062-4e28-449f-8f1f-8b1ffd2974f3")]
        public virtual RepoItemInfo treeItemDeviceListInfo
        {
            get
            {
                return _treeitemdevicelistInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    public partial class ChangeDTMAddressMainViewRepositoryFolders
    {
    }
#pragma warning restore 0436
}