///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace EH.PCPS.TestAutomation.DeviceCare.V10107.Functions.ApplicationArea.Page_Assistant_ConfigureCommDTM.Execution
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ConfigureProfibus recording.
    /// </summary>
    [TestModule("45db6ca6-2706-4d70-ba4d-32404722f3fc", ModuleType.Recording, 1)]
    public partial class ConfigureProfibus : ITestModule
    {
        /// <summary>
        /// Holds an instance of the EH.PCPS.TestAutomation.DeviceCare.V10107.GUI.DeviceCareApplication repository.
        /// </summary>
        public static EH.PCPS.TestAutomation.DeviceCare.V10107.GUI.DeviceCareApplication repo = EH.PCPS.TestAutomation.DeviceCare.V10107.GUI.DeviceCareApplication.Instance;

        static ConfigureProfibus instance = new ConfigureProfibus();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ConfigureProfibus()
        {
            MaxVal = "250";
            MinVal = "0";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ConfigureProfibus Instance
        {
            get { return instance; }
        }

#region Variables

        string _MaxVal;

        /// <summary>
        /// Gets or sets the value of variable MaxVal.
        /// </summary>
        [TestVariable("5b58df48-ea03-4a7c-9b63-2aa9c776512d")]
        public string MaxVal
        {
            get { return _MaxVal; }
            set { _MaxVal = value; }
        }

        string _MinVal;

        /// <summary>
        /// Gets or sets the value of variable MinVal.
        /// </summary>
        [TestVariable("222f2bd3-1bad-4a29-9b17-8ceb0bcf0c98")]
        public string MinVal
        {
            get { return _MinVal; }
            set { _MinVal = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable USBModem.
        /// </summary>
        [TestVariable("8da50cde-8805-4b74-85ef-786120793fae")]
        public string USBModem
        {
            get { return repo.USBModem; }
            set { repo.USBModem = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Baudrate.
        /// </summary>
        [TestVariable("2d7650fd-2ffc-4ae3-9668-6d9e5482954b")]
        public string Baudrate
        {
            get { return repo.Baudrate; }
            set { repo.Baudrate = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DeviceCare.ApplicationArea.Page_Assistant.CommDTMConfigurationPages.OwnConfigurationControls.HARTCommunicationDTM.Combobox_FoundUSBDevices' at CenterRight.", repo.DeviceCare.ApplicationArea.Page_Assistant.CommDTMConfigurationPages.OwnConfigurationControls.HARTCommunicationDTM.Combobox_FoundUSBDevicesInfo, new RecordItemIndex(0));
            repo.DeviceCare.ApplicationArea.Page_Assistant.CommDTMConfigurationPages.OwnConfigurationControls.HARTCommunicationDTM.Combobox_FoundUSBDevices.Click(Location.CenterRight);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DeviceCare.ApplicationArea.Page_Assistant.CommDTMConfigurationPages.OwnConfigurationControls.HARTCommunicationDTM.ListItem_USBModem' at Center.", repo.DeviceCare.ApplicationArea.Page_Assistant.CommDTMConfigurationPages.OwnConfigurationControls.HARTCommunicationDTM.ListItem_USBModemInfo, new RecordItemIndex(1));
            repo.DeviceCare.ApplicationArea.Page_Assistant.CommDTMConfigurationPages.OwnConfigurationControls.HARTCommunicationDTM.ListItem_USBModem.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DeviceCare.ApplicationArea.Page_Assistant.CommDTMConfigurationPages.OwnConfigurationControls.SoftingPROFIDtm.Combobox_PB_Baudrate' at Center.", repo.DeviceCare.ApplicationArea.Page_Assistant.CommDTMConfigurationPages.OwnConfigurationControls.SoftingPROFIDtm.Combobox_PB_BaudrateInfo, new RecordItemIndex(2));
            repo.DeviceCare.ApplicationArea.Page_Assistant.CommDTMConfigurationPages.OwnConfigurationControls.SoftingPROFIDtm.Combobox_PB_Baudrate.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DeviceCare.ApplicationArea.Page_Assistant.CommDTMConfigurationPages.OwnConfigurationControls.SoftingPROFIDtm.ListItem_PB_Baudrate' at Center.", repo.DeviceCare.ApplicationArea.Page_Assistant.CommDTMConfigurationPages.OwnConfigurationControls.SoftingPROFIDtm.ListItem_PB_BaudrateInfo, new RecordItemIndex(3));
            repo.DeviceCare.ApplicationArea.Page_Assistant.CommDTMConfigurationPages.OwnConfigurationControls.SoftingPROFIDtm.ListItem_PB_Baudrate.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Custom to '$MinVal' on item 'DeviceCare.ApplicationArea.Page_Assistant.CommDTMConfigurationPages.OwnConfigurationControls.HARTCommunicationDTM.Text_StartAdress'.", repo.DeviceCare.ApplicationArea.Page_Assistant.CommDTMConfigurationPages.OwnConfigurationControls.HARTCommunicationDTM.Text_StartAdressInfo, new RecordItemIndex(4));
            repo.DeviceCare.ApplicationArea.Page_Assistant.CommDTMConfigurationPages.OwnConfigurationControls.HARTCommunicationDTM.Text_StartAdress.Element.SetAttributeValue("Custom", MinVal);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Custom to '$MaxVal' on item 'DeviceCare.ApplicationArea.Page_Assistant.CommDTMConfigurationPages.OwnConfigurationControls.HARTCommunicationDTM.Text_EndAdress'.", repo.DeviceCare.ApplicationArea.Page_Assistant.CommDTMConfigurationPages.OwnConfigurationControls.HARTCommunicationDTM.Text_EndAdressInfo, new RecordItemIndex(5));
            repo.DeviceCare.ApplicationArea.Page_Assistant.CommDTMConfigurationPages.OwnConfigurationControls.HARTCommunicationDTM.Text_EndAdress.Element.SetAttributeValue("Custom", MaxVal);
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DeviceCare.MenuArea.Menu_DeviceScreen.DTMFunctionMenutop.Scan' at Center.", repo.DeviceCare.MenuArea.Menu_DeviceScreen.DTMFunctionMenutop.ScanInfo, new RecordItemIndex(6));
            //repo.DeviceCare.MenuArea.Menu_DeviceScreen.DTMFunctionMenutop.Scan.Click();
            //Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
