///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace EH.PCPS.TestAutomation.DeviceCare.V10107.Functions.StatusArea.Statusbar.Validation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CheckCommUnitList recording.
    /// </summary>
    [TestModule("30cf5800-4616-4e44-b9ab-6a9834794b57", ModuleType.Recording, 1)]
    public partial class CheckCommUnitList : ITestModule
    {
        /// <summary>
        /// Holds an instance of the EH.PCPS.TestAutomation.DeviceCare.V10107.GUI.DeviceCareApplication repository.
        /// </summary>
        public static EH.PCPS.TestAutomation.DeviceCare.V10107.GUI.DeviceCareApplication repo = EH.PCPS.TestAutomation.DeviceCare.V10107.GUI.DeviceCareApplication.Instance;

        static CheckCommUnitList instance = new CheckCommUnitList();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CheckCommUnitList()
        {
            var_CommUnitName = "FXA195";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CheckCommUnitList Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable var_CommUnitName.
        /// </summary>
        [TestVariable("84123cd4-c7d8-4b36-b096-7e47478822ce")]
        public string var_CommUnitName
        {
            get { return repo.var_CommUnitName; }
            set { repo.var_CommUnitName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DeviceCare.StatusArea.UsbCommunicationUnitList' at Center.", repo.DeviceCare.StatusArea.UsbCommunicationUnitListInfo, new RecordItemIndex(0));
            repo.DeviceCare.StatusArea.UsbCommunicationUnitList.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (Name>$var_CommUnitName) on item 'DeviceCare.StatusArea.UsbCommunicationUnitListElement'.", repo.DeviceCare.StatusArea.UsbCommunicationUnitListElementInfo, new RecordItemIndex(1));
            Validate.Attribute(repo.DeviceCare.StatusArea.UsbCommunicationUnitListElementInfo, "Name", new Regex(Regex.Escape(var_CommUnitName)));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DeviceCare.StatusArea.UsbCommunicationUnitList' at Center.", repo.DeviceCare.StatusArea.UsbCommunicationUnitListInfo, new RecordItemIndex(2));
            repo.DeviceCare.StatusArea.UsbCommunicationUnitList.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
