///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace EH.PCPS.TestAutomation.FieldCare.CI.GUI.ApplicationArea.MainView
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the NetworkViewPaths element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    [RepositoryFolder("b87112a2-0a48-486f-9bec-5e6d3574bcc4")]
    public partial class NetworkViewPaths : RepoGenBaseFolder
    {
        static NetworkViewPaths instance = new NetworkViewPaths();
        RepoItemInfo _networkviewInfo;

        /// <summary>
        /// Gets the singleton class instance representing the NetworkViewPaths element repository.
        /// </summary>
        [RepositoryFolder("b87112a2-0a48-486f-9bec-5e6d3574bcc4")]
        public static NetworkViewPaths Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public NetworkViewPaths() 
            : base("NetworkViewPaths", "/", null, 0, false, "b87112a2-0a48-486f-9bec-5e6d3574bcc4", ".\\RepositoryImages\\NetworkViewPathsb87112a2.rximgres")
        {
            _networkviewInfo = new RepoItemInfo(this, "NetworkView", "/form[@controlname='MDIParent2']/container[@controlname='dockPanelExplorer']/?/?/element[@controltypename='ViewAxHost']/element[@class='SftTreeControl45OCX']", 30000, false, "efbf41d8-e5f3-45a9-9f08-c4896e67f925");
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("b87112a2-0a48-486f-9bec-5e6d3574bcc4")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The NetworkView item.
        /// </summary>
        [RepositoryItem("efbf41d8-e5f3-45a9-9f08-c4896e67f925")]
        public virtual Ranorex.Unknown NetworkView
        {
            get
            {
                 return _networkviewInfo.CreateAdapter<Ranorex.Unknown>(true);
            }
        }

        /// <summary>
        /// The NetworkView item info.
        /// </summary>
        [RepositoryItemInfo("efbf41d8-e5f3-45a9-9f08-c4896e67f925")]
        public virtual RepoItemInfo NetworkViewInfo
        {
            get
            {
                return _networkviewInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    public partial class NetworkViewPathsFolders
    {
    }
#pragma warning restore 0436
}