///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace EH.PCPS.TestAutomation.PrototypeHMI20.EnvelopeCurve.GUI.MenuArea.Toolbar
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the IconsRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    [RepositoryFolder("288ddd5e-4be9-4a3e-aa84-637b4b5577a5")]
    public partial class IconsRepository : RepoGenBaseFolder
    {
        static IconsRepository instance = new IconsRepository();
        RepoItemInfo _buttonnewcurveInfo;
        RepoItemInfo _buttonopencurveInfo;
        RepoItemInfo _buttonsavecurveInfo;
        RepoItemInfo _buttonfirstenvelopecurveInfo;
        RepoItemInfo _buttonpreviousenvelopecurveInfo;
        RepoItemInfo _buttonnextenvelopecurveInfo;
        RepoItemInfo _buttonlastenvelopecurveInfo;
        RepoItemInfo _buttonreadcurveInfo;
        RepoItemInfo _buttonendreadwriteInfo;
        RepoItemInfo _buttonreadsettingsInfo;
        RepoItemInfo _buttoncyclicreadInfo;
        RepoItemInfo _buttoncyclicreadsettingsInfo;
        RepoItemInfo _buttonreadreferencecurveInfo;
        RepoItemInfo _buttonreaddiagnosticcurvesInfo;
        RepoItemInfo _buttonresetreadingrangeInfo;
        RepoItemInfo _buttonresetzoomareaInfo;
        RepoItemInfo _buttonundozoomInfo;
        RepoItemInfo _buttonselectedcurvesInfo;
        RepoItemInfo _buttonfastreverseInfo;
        RepoItemInfo _buttonreverseInfo;
        RepoItemInfo _buttonstopInfo;
        RepoItemInfo _buttonpauseInfo;
        RepoItemInfo _buttonforwardInfo;
        RepoItemInfo _buttonfastforwardInfo;
        RepoItemInfo _buttontanktraceviewInfo;
        RepoItemInfo _buttonsaverestoreInfo;
        RepoItemInfo _buttonlinearizationtableonlineInfo;
        RepoItemInfo _buttonenvelopecurveInfo;
        RepoItemInfo _buttoncreatedocumentationInfo;
        RepoItemInfo _buttoncomparedatasetsInfo;
        RepoItemInfo _buttoneventlistextendedhistoromInfo;
        RepoItemInfo _buttonaboutInfo;
        RepoItemInfo _buttoncontentsInfo;

        /// <summary>
        /// Gets the singleton class instance representing the IconsRepository element repository.
        /// </summary>
        [RepositoryFolder("288ddd5e-4be9-4a3e-aa84-637b4b5577a5")]
        public static IconsRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public IconsRepository() 
            : base("IconsRepository", "/", null, 0, false, "288ddd5e-4be9-4a3e-aa84-637b4b5577a5", ".\\RepositoryImages\\IconsRepository288ddd5e.rximgres")
        {
            _buttonnewcurveInfo = new RepoItemInfo(this, "buttonNewCurve", "/container[@automationid='EnvelopeCurveModule.EnvelopeCurveForm.Form']/container[@controlname='EnvelopeCurveModule.ToolBarStub.Toolbar']/element[@controlname='barDockControlTop']/element/toolbar/button[@childindex='0']", 30000, null, "bd785d57-0f76-427a-a728-6919956d9ae4");
            _buttonopencurveInfo = new RepoItemInfo(this, "buttonOpenCurve", "/container[@automationid='EnvelopeCurveModule.EnvelopeCurveForm.Form']/container[@controlname='EnvelopeCurveModule.ToolBarStub.Toolbar']/element[@controlname='barDockControlTop']/element/toolbar/button[@childindex='1']", 30000, null, "81bc2f61-71f8-41d0-94f3-e5cfd2727ff0");
            _buttonsavecurveInfo = new RepoItemInfo(this, "buttonSaveCurve", "/container[@automationid='EnvelopeCurveModule.EnvelopeCurveForm.Form']/container[@controlname='EnvelopeCurveModule.ToolBarStub.Toolbar']/element[@controlname='barDockControlTop']/element/toolbar/button[@childindex='2']", 30000, null, "1a86d0a9-360b-427e-96d7-0bce68829cb1");
            _buttonfirstenvelopecurveInfo = new RepoItemInfo(this, "buttonFirstEnvelopeCurve", "/container[@automationid='EnvelopeCurveModule.EnvelopeCurveForm.Form']/container[@controlname='EnvelopeCurveModule.ToolBarStub.Toolbar']/element[@controlname='barDockControlTop']/element/toolbar/button[@childindex='3']", 30000, null, "6ee627a0-2b48-480f-99ee-7b37001d46f7");
            _buttonpreviousenvelopecurveInfo = new RepoItemInfo(this, "buttonPreviousEnvelopeCurve", "/container[@automationid='EnvelopeCurveModule.EnvelopeCurveForm.Form']/container[@controlname='EnvelopeCurveModule.ToolBarStub.Toolbar']/element[@controlname='barDockControlTop']/element/toolbar/button[@childindex='4']", 30000, null, "dfe87479-dde2-4df9-99e0-2fc89d09e2f7");
            _buttonnextenvelopecurveInfo = new RepoItemInfo(this, "buttonNextEnvelopeCurve", "/container[@automationid='EnvelopeCurveModule.EnvelopeCurveForm.Form']/container[@controlname='EnvelopeCurveModule.ToolBarStub.Toolbar']/element[@controlname='barDockControlTop']/element/toolbar/button[@childindex='5']", 30000, null, "4a13e89a-0ee8-4822-bcdd-6d3433502c75");
            _buttonlastenvelopecurveInfo = new RepoItemInfo(this, "buttonLastEnvelopeCurve", "/container[@automationid='EnvelopeCurveModule.EnvelopeCurveForm.Form']/container[@controlname='EnvelopeCurveModule.ToolBarStub.Toolbar']/element[@controlname='barDockControlTop']/element/toolbar/button[@childindex='6']", 30000, null, "1ff5a72a-dbf3-4059-96bb-773f5ac2dbe3");
            _buttonreadcurveInfo = new RepoItemInfo(this, "buttonReadCurve", "/container[@automationid='EnvelopeCurveModule.EnvelopeCurveForm.Form']/container[@controlname='EnvelopeCurveModule.ToolBarStub.Toolbar']/element[@controlname='barDockControlTop']/element/toolbar/button[@childindex='7']", 30000, null, "78e01a1b-5e97-48b2-9800-a693dcd1d646");
            _buttonendreadwriteInfo = new RepoItemInfo(this, "buttonEndReadWrite", "/container[@automationid='EnvelopeCurveModule.EnvelopeCurveForm.Form']/container[@controlname='EnvelopeCurveModule.ToolBarStub.Toolbar']/element[@controlname='barDockControlTop']/element/toolbar/button[@childindex='8']", 30000, null, "7f7b3429-fbc3-4a51-be7a-b68c64f8dddd");
            _buttonreadsettingsInfo = new RepoItemInfo(this, "buttonReadSettings", "/container[@automationid='EnvelopeCurveModule.EnvelopeCurveForm.Form']/container[@controlname='EnvelopeCurveModule.ToolBarStub.Toolbar']/element[@controlname='barDockControlTop']/element/toolbar/button[@childindex='9']", 30000, null, "48fbd275-dd2b-4ff6-a88e-f49157e74d15");
            _buttoncyclicreadInfo = new RepoItemInfo(this, "buttonCyclicRead", "/container[@automationid='EnvelopeCurveModule.EnvelopeCurveForm.Form']/container[@controlname='EnvelopeCurveModule.ToolBarStub.Toolbar']/element[@controlname='barDockControlTop']/element/toolbar/button[@childindex='10']", 30000, null, "96c5fda9-630a-4d62-8ec9-c40ed1928705");
            _buttoncyclicreadsettingsInfo = new RepoItemInfo(this, "buttonCyclicReadSettings", "/container[@automationid='EnvelopeCurveModule.EnvelopeCurveForm.Form']/container[@controlname='EnvelopeCurveModule.ToolBarStub.Toolbar']/element[@controlname='barDockControlTop']/element/toolbar/button[@childindex='11']", 30000, null, "ad5a303f-2180-4d92-aad4-123b09ce10e2");
            _buttonreadreferencecurveInfo = new RepoItemInfo(this, "buttonReadReferenceCurve", "/container[@automationid='EnvelopeCurveModule.EnvelopeCurveForm.Form']/container[@controlname='EnvelopeCurveModule.ToolBarStub.Toolbar']/element[@controlname='barDockControlTop']/element/toolbar/button[@childindex='12']", 30000, null, "02957160-1bf6-4df2-9e97-f916ee3cd770");
            _buttonreaddiagnosticcurvesInfo = new RepoItemInfo(this, "buttonReadDiagnosticCurves", "/container[@automationid='EnvelopeCurveModule.EnvelopeCurveForm.Form']/container[@controlname='EnvelopeCurveModule.ToolBarStub.Toolbar']/element[@controlname='barDockControlTop']/element/toolbar/button[@childindex='13']", 30000, null, "ed11a38d-0cc1-45f8-93b3-a0dcb4a5300c");
            _buttonresetreadingrangeInfo = new RepoItemInfo(this, "buttonResetReadingRange", "/container[@automationid='EnvelopeCurveModule.EnvelopeCurveForm.Form']/container[@controlname='EnvelopeCurveModule.ToolBarStub.Toolbar']/element[@controlname='barDockControlTop']/element/toolbar/button[@childindex='14']", 30000, null, "22168811-eb4a-40ea-aebc-fdf020fdc6d3");
            _buttonresetzoomareaInfo = new RepoItemInfo(this, "buttonResetZoomArea", "/container[@automationid='EnvelopeCurveModule.EnvelopeCurveForm.Form']/container[@controlname='EnvelopeCurveModule.ToolBarStub.Toolbar']/element[@controlname='barDockControlTop']/element/toolbar/button[@childindex='15']", 30000, null, "79fd9153-10aa-47bd-82b9-2640c94794ca");
            _buttonundozoomInfo = new RepoItemInfo(this, "buttonUndoZoom", "/container[@automationid='EnvelopeCurveModule.EnvelopeCurveForm.Form']/container[@controlname='EnvelopeCurveModule.ToolBarStub.Toolbar']/element[@controlname='barDockControlTop']/element/toolbar/button[@childindex='16']", 30000, null, "ced13460-273d-4f43-938d-bd8289d62a13");
            _buttonselectedcurvesInfo = new RepoItemInfo(this, "buttonSelectedCurves", "/container[@automationid='EnvelopeCurveModule.EnvelopeCurveForm.Form']/container[@controlname='EnvelopeCurveModule.ToolBarStub.Toolbar']/element[@controlname='barDockControlTop']/element/toolbar/button[@childindex='17']", 30000, null, "e83e36b1-76ca-4335-9255-aaa1d4147ea1");
            _buttonfastreverseInfo = new RepoItemInfo(this, "buttonFastReverse", "/container[@automationid='EnvelopeCurveModule.EnvelopeCurveForm.Form']/container[@controlname='EnvelopeCurveModule.ToolBarStub.Toolbar']/element[@controlname='barDockControlTop']/element/toolbar/button[@childindex='18']", 30000, null, "96263b2d-5071-473b-88ce-6c720c17ba41");
            _buttonreverseInfo = new RepoItemInfo(this, "buttonReverse", "/container[@automationid='EnvelopeCurveModule.EnvelopeCurveForm.Form']/container[@controlname='EnvelopeCurveModule.ToolBarStub.Toolbar']/element[@controlname='barDockControlTop']/element/toolbar/button[@childindex='19']", 30000, null, "09bcdfba-8ae1-479c-8ec0-db01343c0d7d");
            _buttonstopInfo = new RepoItemInfo(this, "buttonStop", "/container[@automationid='EnvelopeCurveModule.EnvelopeCurveForm.Form']/container[@controlname='EnvelopeCurveModule.ToolBarStub.Toolbar']/element[@controlname='barDockControlTop']/element/toolbar/button[@childindex='20']", 30000, null, "06ec903b-07f8-4e06-838b-3be444b63a6a");
            _buttonpauseInfo = new RepoItemInfo(this, "buttonPause", "/container[@automationid='EnvelopeCurveModule.EnvelopeCurveForm.Form']/container[@controlname='EnvelopeCurveModule.ToolBarStub.Toolbar']/element[@controlname='barDockControlTop']/element/toolbar/button[@childindex='21']", 30000, null, "7d7fdf54-9a1b-4e5f-b9f4-9955b7130a42");
            _buttonforwardInfo = new RepoItemInfo(this, "buttonForward", "/container[@automationid='EnvelopeCurveModule.EnvelopeCurveForm.Form']/container[@controlname='EnvelopeCurveModule.ToolBarStub.Toolbar']/element[@controlname='barDockControlTop']/element/toolbar/button[@childindex='22']", 30000, null, "86b67793-b4f9-40ed-bb04-37b27053fead");
            _buttonfastforwardInfo = new RepoItemInfo(this, "buttonFastForward", "/container[@automationid='EnvelopeCurveModule.EnvelopeCurveForm.Form']/container[@controlname='EnvelopeCurveModule.ToolBarStub.Toolbar']/element[@controlname='barDockControlTop']/element/toolbar/button[@childindex='23']", 30000, null, "4555396a-1fa0-4e07-8166-4078b125ff08");
            _buttontanktraceviewInfo = new RepoItemInfo(this, "buttonTankTraceView", "/container[@automationid='EnvelopeCurveModule.EnvelopeCurveForm.Form']/container[@controlname='EnvelopeCurveModule.ToolBarStub.Toolbar']/element[@controlname='barDockControlTop']/element/toolbar/button[@childindex='24']", 30000, null, "ecf8a93b-9f17-4607-b378-4dc7259f5426");
            _buttonsaverestoreInfo = new RepoItemInfo(this, "buttonSaveRestore", "/container[@automationid='EnvelopeCurveModule.EnvelopeCurveForm.Form']/container[@controlname='EnvelopeCurveModule.ToolBarStub.Toolbar']/element[@controlname='barDockControlTop']/element/toolbar/button[@childindex='25']", 30000, null, "5d9f9525-cfd8-44ab-871b-66309f6f9543");
            _buttonlinearizationtableonlineInfo = new RepoItemInfo(this, "buttonLinearizationTableOnline", "/container[@automationid='EnvelopeCurveModule.EnvelopeCurveForm.Form']/container[@controlname='EnvelopeCurveModule.ToolBarStub.Toolbar']/element[@controlname='barDockControlTop']/element/toolbar/button[@childindex='26']", 30000, null, "6258bb1d-38ef-4902-a258-9c05b08e9db2");
            _buttonenvelopecurveInfo = new RepoItemInfo(this, "buttonEnvelopeCurve", "/container[@automationid='EnvelopeCurveModule.EnvelopeCurveForm.Form']/container[@controlname='EnvelopeCurveModule.ToolBarStub.Toolbar']/element[@controlname='barDockControlTop']/element/toolbar/button[@childindex='27']", 30000, null, "93acc259-884d-48f3-9369-6a74e80f4fd5");
            _buttoncreatedocumentationInfo = new RepoItemInfo(this, "buttonCreateDocumentation", "/container[@automationid='EnvelopeCurveModule.EnvelopeCurveForm.Form']/container[@controlname='EnvelopeCurveModule.ToolBarStub.Toolbar']/element[@controlname='barDockControlTop']/element/toolbar/button[@childindex='28']", 30000, null, "39decbb3-4797-4506-b732-eac25e7ff245");
            _buttoncomparedatasetsInfo = new RepoItemInfo(this, "buttonCompareDatasets", "/container[@automationid='EnvelopeCurveModule.EnvelopeCurveForm.Form']/container[@controlname='EnvelopeCurveModule.ToolBarStub.Toolbar']/element[@controlname='barDockControlTop']/element/toolbar/button[@childindex='29']", 30000, null, "6f937d56-9bb1-4724-91a1-05a30eac9dac");
            _buttoneventlistextendedhistoromInfo = new RepoItemInfo(this, "buttonEventlistExtendedHistoROM", "/container[@automationid='EnvelopeCurveModule.EnvelopeCurveForm.Form']/container[@controlname='EnvelopeCurveModule.ToolBarStub.Toolbar']/element[@controlname='barDockControlTop']/element/toolbar/button[@childindex='30']", 30000, null, "23afdb39-4925-4a2c-a4bf-aee7249f0b37");
            _buttonaboutInfo = new RepoItemInfo(this, "buttonAbout", "/container[@automationid='EnvelopeCurveModule.EnvelopeCurveForm.Form']/container[@controlname='EnvelopeCurveModule.ToolBarStub.Toolbar']/element[@controlname='barDockControlTop']/element/toolbar/button[@childindex='31']", 30000, null, "b7f218d6-7a11-489d-adb0-47aef2f089c5");
            _buttoncontentsInfo = new RepoItemInfo(this, "buttonContents", "/container[@automationid='EnvelopeCurveModule.EnvelopeCurveForm.Form']/container[@controlname='EnvelopeCurveModule.ToolBarStub.Toolbar']/element[@controlname='barDockControlTop']/element/toolbar/button[@childindex='32']", 30000, null, "a7aba89b-33af-4fd4-87fd-5c7528d7233d");
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("288ddd5e-4be9-4a3e-aa84-637b4b5577a5")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The buttonNewCurve item.
        /// </summary>
        [RepositoryItem("bd785d57-0f76-427a-a728-6919956d9ae4")]
        public virtual Ranorex.Button buttonNewCurve
        {
            get
            {
                 return _buttonnewcurveInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonNewCurve item info.
        /// </summary>
        [RepositoryItemInfo("bd785d57-0f76-427a-a728-6919956d9ae4")]
        public virtual RepoItemInfo buttonNewCurveInfo
        {
            get
            {
                return _buttonnewcurveInfo;
            }
        }

        /// <summary>
        /// The buttonOpenCurve item.
        /// </summary>
        [RepositoryItem("81bc2f61-71f8-41d0-94f3-e5cfd2727ff0")]
        public virtual Ranorex.Button buttonOpenCurve
        {
            get
            {
                 return _buttonopencurveInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonOpenCurve item info.
        /// </summary>
        [RepositoryItemInfo("81bc2f61-71f8-41d0-94f3-e5cfd2727ff0")]
        public virtual RepoItemInfo buttonOpenCurveInfo
        {
            get
            {
                return _buttonopencurveInfo;
            }
        }

        /// <summary>
        /// The buttonSaveCurve item.
        /// </summary>
        [RepositoryItem("1a86d0a9-360b-427e-96d7-0bce68829cb1")]
        public virtual Ranorex.Button buttonSaveCurve
        {
            get
            {
                 return _buttonsavecurveInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonSaveCurve item info.
        /// </summary>
        [RepositoryItemInfo("1a86d0a9-360b-427e-96d7-0bce68829cb1")]
        public virtual RepoItemInfo buttonSaveCurveInfo
        {
            get
            {
                return _buttonsavecurveInfo;
            }
        }

        /// <summary>
        /// The buttonFirstEnvelopeCurve item.
        /// </summary>
        [RepositoryItem("6ee627a0-2b48-480f-99ee-7b37001d46f7")]
        public virtual Ranorex.Button buttonFirstEnvelopeCurve
        {
            get
            {
                 return _buttonfirstenvelopecurveInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonFirstEnvelopeCurve item info.
        /// </summary>
        [RepositoryItemInfo("6ee627a0-2b48-480f-99ee-7b37001d46f7")]
        public virtual RepoItemInfo buttonFirstEnvelopeCurveInfo
        {
            get
            {
                return _buttonfirstenvelopecurveInfo;
            }
        }

        /// <summary>
        /// The buttonPreviousEnvelopeCurve item.
        /// </summary>
        [RepositoryItem("dfe87479-dde2-4df9-99e0-2fc89d09e2f7")]
        public virtual Ranorex.Button buttonPreviousEnvelopeCurve
        {
            get
            {
                 return _buttonpreviousenvelopecurveInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonPreviousEnvelopeCurve item info.
        /// </summary>
        [RepositoryItemInfo("dfe87479-dde2-4df9-99e0-2fc89d09e2f7")]
        public virtual RepoItemInfo buttonPreviousEnvelopeCurveInfo
        {
            get
            {
                return _buttonpreviousenvelopecurveInfo;
            }
        }

        /// <summary>
        /// The buttonNextEnvelopeCurve item.
        /// </summary>
        [RepositoryItem("4a13e89a-0ee8-4822-bcdd-6d3433502c75")]
        public virtual Ranorex.Button buttonNextEnvelopeCurve
        {
            get
            {
                 return _buttonnextenvelopecurveInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonNextEnvelopeCurve item info.
        /// </summary>
        [RepositoryItemInfo("4a13e89a-0ee8-4822-bcdd-6d3433502c75")]
        public virtual RepoItemInfo buttonNextEnvelopeCurveInfo
        {
            get
            {
                return _buttonnextenvelopecurveInfo;
            }
        }

        /// <summary>
        /// The buttonLastEnvelopeCurve item.
        /// </summary>
        [RepositoryItem("1ff5a72a-dbf3-4059-96bb-773f5ac2dbe3")]
        public virtual Ranorex.Button buttonLastEnvelopeCurve
        {
            get
            {
                 return _buttonlastenvelopecurveInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonLastEnvelopeCurve item info.
        /// </summary>
        [RepositoryItemInfo("1ff5a72a-dbf3-4059-96bb-773f5ac2dbe3")]
        public virtual RepoItemInfo buttonLastEnvelopeCurveInfo
        {
            get
            {
                return _buttonlastenvelopecurveInfo;
            }
        }

        /// <summary>
        /// The buttonReadCurve item.
        /// </summary>
        [RepositoryItem("78e01a1b-5e97-48b2-9800-a693dcd1d646")]
        public virtual Ranorex.Button buttonReadCurve
        {
            get
            {
                 return _buttonreadcurveInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonReadCurve item info.
        /// </summary>
        [RepositoryItemInfo("78e01a1b-5e97-48b2-9800-a693dcd1d646")]
        public virtual RepoItemInfo buttonReadCurveInfo
        {
            get
            {
                return _buttonreadcurveInfo;
            }
        }

        /// <summary>
        /// The buttonEndReadWrite item.
        /// </summary>
        [RepositoryItem("7f7b3429-fbc3-4a51-be7a-b68c64f8dddd")]
        public virtual Ranorex.Button buttonEndReadWrite
        {
            get
            {
                 return _buttonendreadwriteInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonEndReadWrite item info.
        /// </summary>
        [RepositoryItemInfo("7f7b3429-fbc3-4a51-be7a-b68c64f8dddd")]
        public virtual RepoItemInfo buttonEndReadWriteInfo
        {
            get
            {
                return _buttonendreadwriteInfo;
            }
        }

        /// <summary>
        /// The buttonReadSettings item.
        /// </summary>
        [RepositoryItem("48fbd275-dd2b-4ff6-a88e-f49157e74d15")]
        public virtual Ranorex.Button buttonReadSettings
        {
            get
            {
                 return _buttonreadsettingsInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonReadSettings item info.
        /// </summary>
        [RepositoryItemInfo("48fbd275-dd2b-4ff6-a88e-f49157e74d15")]
        public virtual RepoItemInfo buttonReadSettingsInfo
        {
            get
            {
                return _buttonreadsettingsInfo;
            }
        }

        /// <summary>
        /// The buttonCyclicRead item.
        /// </summary>
        [RepositoryItem("96c5fda9-630a-4d62-8ec9-c40ed1928705")]
        public virtual Ranorex.Button buttonCyclicRead
        {
            get
            {
                 return _buttoncyclicreadInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonCyclicRead item info.
        /// </summary>
        [RepositoryItemInfo("96c5fda9-630a-4d62-8ec9-c40ed1928705")]
        public virtual RepoItemInfo buttonCyclicReadInfo
        {
            get
            {
                return _buttoncyclicreadInfo;
            }
        }

        /// <summary>
        /// The buttonCyclicReadSettings item.
        /// </summary>
        [RepositoryItem("ad5a303f-2180-4d92-aad4-123b09ce10e2")]
        public virtual Ranorex.Button buttonCyclicReadSettings
        {
            get
            {
                 return _buttoncyclicreadsettingsInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonCyclicReadSettings item info.
        /// </summary>
        [RepositoryItemInfo("ad5a303f-2180-4d92-aad4-123b09ce10e2")]
        public virtual RepoItemInfo buttonCyclicReadSettingsInfo
        {
            get
            {
                return _buttoncyclicreadsettingsInfo;
            }
        }

        /// <summary>
        /// The buttonReadReferenceCurve item.
        /// </summary>
        [RepositoryItem("02957160-1bf6-4df2-9e97-f916ee3cd770")]
        public virtual Ranorex.Button buttonReadReferenceCurve
        {
            get
            {
                 return _buttonreadreferencecurveInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonReadReferenceCurve item info.
        /// </summary>
        [RepositoryItemInfo("02957160-1bf6-4df2-9e97-f916ee3cd770")]
        public virtual RepoItemInfo buttonReadReferenceCurveInfo
        {
            get
            {
                return _buttonreadreferencecurveInfo;
            }
        }

        /// <summary>
        /// The buttonReadDiagnosticCurves item.
        /// </summary>
        [RepositoryItem("ed11a38d-0cc1-45f8-93b3-a0dcb4a5300c")]
        public virtual Ranorex.Button buttonReadDiagnosticCurves
        {
            get
            {
                 return _buttonreaddiagnosticcurvesInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonReadDiagnosticCurves item info.
        /// </summary>
        [RepositoryItemInfo("ed11a38d-0cc1-45f8-93b3-a0dcb4a5300c")]
        public virtual RepoItemInfo buttonReadDiagnosticCurvesInfo
        {
            get
            {
                return _buttonreaddiagnosticcurvesInfo;
            }
        }

        /// <summary>
        /// The buttonResetReadingRange item.
        /// </summary>
        [RepositoryItem("22168811-eb4a-40ea-aebc-fdf020fdc6d3")]
        public virtual Ranorex.Button buttonResetReadingRange
        {
            get
            {
                 return _buttonresetreadingrangeInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonResetReadingRange item info.
        /// </summary>
        [RepositoryItemInfo("22168811-eb4a-40ea-aebc-fdf020fdc6d3")]
        public virtual RepoItemInfo buttonResetReadingRangeInfo
        {
            get
            {
                return _buttonresetreadingrangeInfo;
            }
        }

        /// <summary>
        /// The buttonResetZoomArea item.
        /// </summary>
        [RepositoryItem("79fd9153-10aa-47bd-82b9-2640c94794ca")]
        public virtual Ranorex.Button buttonResetZoomArea
        {
            get
            {
                 return _buttonresetzoomareaInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonResetZoomArea item info.
        /// </summary>
        [RepositoryItemInfo("79fd9153-10aa-47bd-82b9-2640c94794ca")]
        public virtual RepoItemInfo buttonResetZoomAreaInfo
        {
            get
            {
                return _buttonresetzoomareaInfo;
            }
        }

        /// <summary>
        /// The buttonUndoZoom item.
        /// </summary>
        [RepositoryItem("ced13460-273d-4f43-938d-bd8289d62a13")]
        public virtual Ranorex.Button buttonUndoZoom
        {
            get
            {
                 return _buttonundozoomInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonUndoZoom item info.
        /// </summary>
        [RepositoryItemInfo("ced13460-273d-4f43-938d-bd8289d62a13")]
        public virtual RepoItemInfo buttonUndoZoomInfo
        {
            get
            {
                return _buttonundozoomInfo;
            }
        }

        /// <summary>
        /// The buttonSelectedCurves item.
        /// </summary>
        [RepositoryItem("e83e36b1-76ca-4335-9255-aaa1d4147ea1")]
        public virtual Ranorex.Button buttonSelectedCurves
        {
            get
            {
                 return _buttonselectedcurvesInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonSelectedCurves item info.
        /// </summary>
        [RepositoryItemInfo("e83e36b1-76ca-4335-9255-aaa1d4147ea1")]
        public virtual RepoItemInfo buttonSelectedCurvesInfo
        {
            get
            {
                return _buttonselectedcurvesInfo;
            }
        }

        /// <summary>
        /// The buttonFastReverse item.
        /// </summary>
        [RepositoryItem("96263b2d-5071-473b-88ce-6c720c17ba41")]
        public virtual Ranorex.Button buttonFastReverse
        {
            get
            {
                 return _buttonfastreverseInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonFastReverse item info.
        /// </summary>
        [RepositoryItemInfo("96263b2d-5071-473b-88ce-6c720c17ba41")]
        public virtual RepoItemInfo buttonFastReverseInfo
        {
            get
            {
                return _buttonfastreverseInfo;
            }
        }

        /// <summary>
        /// The buttonReverse item.
        /// </summary>
        [RepositoryItem("09bcdfba-8ae1-479c-8ec0-db01343c0d7d")]
        public virtual Ranorex.Button buttonReverse
        {
            get
            {
                 return _buttonreverseInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonReverse item info.
        /// </summary>
        [RepositoryItemInfo("09bcdfba-8ae1-479c-8ec0-db01343c0d7d")]
        public virtual RepoItemInfo buttonReverseInfo
        {
            get
            {
                return _buttonreverseInfo;
            }
        }

        /// <summary>
        /// The buttonStop item.
        /// </summary>
        [RepositoryItem("06ec903b-07f8-4e06-838b-3be444b63a6a")]
        public virtual Ranorex.Button buttonStop
        {
            get
            {
                 return _buttonstopInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonStop item info.
        /// </summary>
        [RepositoryItemInfo("06ec903b-07f8-4e06-838b-3be444b63a6a")]
        public virtual RepoItemInfo buttonStopInfo
        {
            get
            {
                return _buttonstopInfo;
            }
        }

        /// <summary>
        /// The buttonPause item.
        /// </summary>
        [RepositoryItem("7d7fdf54-9a1b-4e5f-b9f4-9955b7130a42")]
        public virtual Ranorex.Button buttonPause
        {
            get
            {
                 return _buttonpauseInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonPause item info.
        /// </summary>
        [RepositoryItemInfo("7d7fdf54-9a1b-4e5f-b9f4-9955b7130a42")]
        public virtual RepoItemInfo buttonPauseInfo
        {
            get
            {
                return _buttonpauseInfo;
            }
        }

        /// <summary>
        /// The buttonForward item.
        /// </summary>
        [RepositoryItem("86b67793-b4f9-40ed-bb04-37b27053fead")]
        public virtual Ranorex.Button buttonForward
        {
            get
            {
                 return _buttonforwardInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonForward item info.
        /// </summary>
        [RepositoryItemInfo("86b67793-b4f9-40ed-bb04-37b27053fead")]
        public virtual RepoItemInfo buttonForwardInfo
        {
            get
            {
                return _buttonforwardInfo;
            }
        }

        /// <summary>
        /// The buttonFastForward item.
        /// </summary>
        [RepositoryItem("4555396a-1fa0-4e07-8166-4078b125ff08")]
        public virtual Ranorex.Button buttonFastForward
        {
            get
            {
                 return _buttonfastforwardInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonFastForward item info.
        /// </summary>
        [RepositoryItemInfo("4555396a-1fa0-4e07-8166-4078b125ff08")]
        public virtual RepoItemInfo buttonFastForwardInfo
        {
            get
            {
                return _buttonfastforwardInfo;
            }
        }

        /// <summary>
        /// The buttonTankTraceView item.
        /// </summary>
        [RepositoryItem("ecf8a93b-9f17-4607-b378-4dc7259f5426")]
        public virtual Ranorex.Button buttonTankTraceView
        {
            get
            {
                 return _buttontanktraceviewInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonTankTraceView item info.
        /// </summary>
        [RepositoryItemInfo("ecf8a93b-9f17-4607-b378-4dc7259f5426")]
        public virtual RepoItemInfo buttonTankTraceViewInfo
        {
            get
            {
                return _buttontanktraceviewInfo;
            }
        }

        /// <summary>
        /// The buttonSaveRestore item.
        /// </summary>
        [RepositoryItem("5d9f9525-cfd8-44ab-871b-66309f6f9543")]
        public virtual Ranorex.Button buttonSaveRestore
        {
            get
            {
                 return _buttonsaverestoreInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonSaveRestore item info.
        /// </summary>
        [RepositoryItemInfo("5d9f9525-cfd8-44ab-871b-66309f6f9543")]
        public virtual RepoItemInfo buttonSaveRestoreInfo
        {
            get
            {
                return _buttonsaverestoreInfo;
            }
        }

        /// <summary>
        /// The buttonLinearizationTableOnline item.
        /// </summary>
        [RepositoryItem("6258bb1d-38ef-4902-a258-9c05b08e9db2")]
        public virtual Ranorex.Button buttonLinearizationTableOnline
        {
            get
            {
                 return _buttonlinearizationtableonlineInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonLinearizationTableOnline item info.
        /// </summary>
        [RepositoryItemInfo("6258bb1d-38ef-4902-a258-9c05b08e9db2")]
        public virtual RepoItemInfo buttonLinearizationTableOnlineInfo
        {
            get
            {
                return _buttonlinearizationtableonlineInfo;
            }
        }

        /// <summary>
        /// The buttonEnvelopeCurve item.
        /// </summary>
        [RepositoryItem("93acc259-884d-48f3-9369-6a74e80f4fd5")]
        public virtual Ranorex.Button buttonEnvelopeCurve
        {
            get
            {
                 return _buttonenvelopecurveInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonEnvelopeCurve item info.
        /// </summary>
        [RepositoryItemInfo("93acc259-884d-48f3-9369-6a74e80f4fd5")]
        public virtual RepoItemInfo buttonEnvelopeCurveInfo
        {
            get
            {
                return _buttonenvelopecurveInfo;
            }
        }

        /// <summary>
        /// The buttonCreateDocumentation item.
        /// </summary>
        [RepositoryItem("39decbb3-4797-4506-b732-eac25e7ff245")]
        public virtual Ranorex.Button buttonCreateDocumentation
        {
            get
            {
                 return _buttoncreatedocumentationInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonCreateDocumentation item info.
        /// </summary>
        [RepositoryItemInfo("39decbb3-4797-4506-b732-eac25e7ff245")]
        public virtual RepoItemInfo buttonCreateDocumentationInfo
        {
            get
            {
                return _buttoncreatedocumentationInfo;
            }
        }

        /// <summary>
        /// The buttonCompareDatasets item.
        /// </summary>
        [RepositoryItem("6f937d56-9bb1-4724-91a1-05a30eac9dac")]
        public virtual Ranorex.Button buttonCompareDatasets
        {
            get
            {
                 return _buttoncomparedatasetsInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonCompareDatasets item info.
        /// </summary>
        [RepositoryItemInfo("6f937d56-9bb1-4724-91a1-05a30eac9dac")]
        public virtual RepoItemInfo buttonCompareDatasetsInfo
        {
            get
            {
                return _buttoncomparedatasetsInfo;
            }
        }

        /// <summary>
        /// The buttonEventlistExtendedHistoROM item.
        /// </summary>
        [RepositoryItem("23afdb39-4925-4a2c-a4bf-aee7249f0b37")]
        public virtual Ranorex.Button buttonEventlistExtendedHistoROM
        {
            get
            {
                 return _buttoneventlistextendedhistoromInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonEventlistExtendedHistoROM item info.
        /// </summary>
        [RepositoryItemInfo("23afdb39-4925-4a2c-a4bf-aee7249f0b37")]
        public virtual RepoItemInfo buttonEventlistExtendedHistoROMInfo
        {
            get
            {
                return _buttoneventlistextendedhistoromInfo;
            }
        }

        /// <summary>
        /// The buttonAbout item.
        /// </summary>
        [RepositoryItem("b7f218d6-7a11-489d-adb0-47aef2f089c5")]
        public virtual Ranorex.Button buttonAbout
        {
            get
            {
                 return _buttonaboutInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonAbout item info.
        /// </summary>
        [RepositoryItemInfo("b7f218d6-7a11-489d-adb0-47aef2f089c5")]
        public virtual RepoItemInfo buttonAboutInfo
        {
            get
            {
                return _buttonaboutInfo;
            }
        }

        /// <summary>
        /// The buttonContents item.
        /// </summary>
        [RepositoryItem("a7aba89b-33af-4fd4-87fd-5c7528d7233d")]
        public virtual Ranorex.Button buttonContents
        {
            get
            {
                 return _buttoncontentsInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonContents item info.
        /// </summary>
        [RepositoryItemInfo("a7aba89b-33af-4fd4-87fd-5c7528d7233d")]
        public virtual RepoItemInfo buttonContentsInfo
        {
            get
            {
                return _buttoncontentsInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    public partial class IconsRepositoryFolders
    {
    }
#pragma warning restore 0436
}