///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace EH.PCPS.TestAutomation.TestPackageCI.EnvelopeCurveShed.GUI.MenuArea.Menubar
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the ElementsRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    [RepositoryFolder("3786e64d-e731-4336-8515-e5d826b8505c")]
    public partial class ElementsRepository : RepoGenBaseFolder
    {
        static ElementsRepository instance = new ElementsRepository();
        RepoItemInfo _menuitemenvelopecurveInfo;
        RepoItemInfo _buttonnewcurveInfo;
        RepoItemInfo _buttonopencurveInfo;
        RepoItemInfo _buttonsavecurveInfo;
        RepoItemInfo _buttonsavecurveasInfo;
        RepoItemInfo _elementmenuelementInfo;
        RepoItemInfo _containermenucontainerInfo;
        RepoItemInfo _buttonreadcurveInfo;
        RepoItemInfo _buttoncyclicreadInfo;
        RepoItemInfo _buttonendreadwriteInfo;
        RepoItemInfo _buttonreadsettingsInfo;
        RepoItemInfo _buttoncyclicreadsettingsInfo;
        RepoItemInfo _buttonresetreadingrangeInfo;
        RepoItemInfo _buttonoverlappedcurvesInfo;
        RepoItemInfo _menuitemplaybackInfo;
        RepoItemInfo _menuitemdisplayInfo;
        RepoItemInfo _buttonremarksInfo;
        RepoItemInfo _menuitemlayoutInfo;
        RepoItemInfo _menuitemhelpInfo;
        RepoItemInfo _buttonplaybackselectedcurvesInfo;
        RepoItemInfo _buttonplaybackforwardInfo;
        RepoItemInfo _buttonplaybackfastforwardInfo;
        RepoItemInfo _buttonplaybackreverseInfo;
        RepoItemInfo _buttonplaybackfastreverseInfo;
        RepoItemInfo _buttonplaybackstopInfo;
        RepoItemInfo _buttonplaybackpauseInfo;
        RepoItemInfo _buttondisplayclearplotdisplayInfo;
        RepoItemInfo _buttondisplayzoomandgridsettingsInfo;
        RepoItemInfo _buttondisplayresetzoomareaInfo;
        RepoItemInfo _buttondisplayundozoomInfo;
        RepoItemInfo _buttondisplayfirstenvelopecurveInfo;
        RepoItemInfo _buttondisplaylastenvelopecurveInfo;
        RepoItemInfo _buttondisplaynextenvelopecurveInfo;
        RepoItemInfo _buttondisplaypreviousenvelopecurveInfo;
        RepoItemInfo _buttonlayoutdiagramInfo;
        RepoItemInfo _buttonlayoutdiagramplusinfoInfo;
        RepoItemInfo _buttonhelpcontentsInfo;
        RepoItemInfo _buttonhelpaboutInfo;

        /// <summary>
        /// Gets the singleton class instance representing the ElementsRepository element repository.
        /// </summary>
        [RepositoryFolder("3786e64d-e731-4336-8515-e5d826b8505c")]
        public static ElementsRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public ElementsRepository() 
            : base("ElementsRepository", "/", null, 0, false, "3786e64d-e731-4336-8515-e5d826b8505c", ".\\RepositoryImages\\ElementsRepository3786e64d.rximgres")
        {
            _menuitemenvelopecurveInfo = new RepoItemInfo(this, "menuItemEnvelopeCurve", "/container[@automationid='EnvelopeCurveModule.EnvelopeCurveForm.Form']/container[@controlname='EnvelopeCurveModule.MenuBarStub.Menubar']/element[@controlname='barDockControlTop']/element/menubar/menuitem[@childindex='0']", 30000, null, "3b0a8da4-de1c-4bca-9902-ddabfe053acd");
            _buttonnewcurveInfo = new RepoItemInfo(this, "buttonNewCurve", "/form/element/container/button[@childindex='0']", 30000, null, "348ef014-fcbf-407c-bc1d-b4bac1c1d3ab");
            _buttonopencurveInfo = new RepoItemInfo(this, "buttonOpenCurve", "/form/element/container/button[@childindex='1']", 30000, null, "b4a5636a-8525-453a-bed2-a255da4cf419");
            _buttonsavecurveInfo = new RepoItemInfo(this, "buttonSaveCurve", "/form/element/container/button[@childindex='2']", 30000, null, "a8c11b17-f120-43eb-9532-bcf2ae0de394");
            _buttonsavecurveasInfo = new RepoItemInfo(this, "buttonSaveCurveAs", "/form/element/container/button[@childindex='3']", 30000, null, "03da229c-40d2-4992-9847-a63f425039b9");
            _elementmenuelementInfo = new RepoItemInfo(this, "elementMenuElement", "/form[@controltypename='SubMenuControlForm']/element", 30000, null, "7fe8bf68-6bfe-493f-9d53-32d81114d1ae");
            _containermenucontainerInfo = new RepoItemInfo(this, "containerMenuContainer", "/form[@controltypename='SubMenuControlForm']/element/container", 30000, null, "44255b92-0288-4d0e-8798-5a410727c82b");
            _buttonreadcurveInfo = new RepoItemInfo(this, "buttonReadCurve", "/form/element/container/button[@childindex='4']", 30000, null, "ed07aa80-9e8b-45ec-9f18-04b48e9a0803");
            _buttoncyclicreadInfo = new RepoItemInfo(this, "buttonCyclicRead", "/form/element/container/button[@childindex='5']", 30000, null, "6769f89d-d2c5-41c4-ae49-72483101801a");
            _buttonendreadwriteInfo = new RepoItemInfo(this, "buttonEndReadWrite", "/form/element/container/button[@childindex='6']", 30000, null, "b8277938-8f12-444c-af07-67c458b001d9");
            _buttonreadsettingsInfo = new RepoItemInfo(this, "buttonReadSettings", "/form/element/container/button[@childindex='7']", 30000, null, "1f277284-548a-4d1a-9c7b-9844c6fb0a9f");
            _buttoncyclicreadsettingsInfo = new RepoItemInfo(this, "buttonCyclicReadSettings", "/form/element/container/button[@childindex='8']", 30000, null, "ce5bcef4-2e8b-49a5-aca1-f13b711d579b");
            _buttonresetreadingrangeInfo = new RepoItemInfo(this, "buttonResetReadingRange", "/form/element/container/button[@childindex='9']", 30000, null, "0f6d56ca-2d6e-4356-af7f-451f27dfad1b");
            _buttonoverlappedcurvesInfo = new RepoItemInfo(this, "buttonOverlappedCurves", "/form/element/container/button[@childindex='10']", 30000, null, "9c1a5c97-9a9a-4dc7-b44b-00ce1fa0e874");
            _menuitemplaybackInfo = new RepoItemInfo(this, "menuItemPlayBack", "/form/element/container/menuitem[@childindex='11']", 30000, null, "86e286ca-2db3-4b52-b2da-04273a2c88b2");
            _menuitemdisplayInfo = new RepoItemInfo(this, "menuItemDisplay", "/form/element/container/menuitem[@childindex='12']", 30000, null, "0e2aa8fc-d00e-457b-81f0-e83a505ceff4");
            _buttonremarksInfo = new RepoItemInfo(this, "buttonRemarks", "/form/element/container/button[@childindex='13']", 30000, null, "1ea30c6e-7b6d-46a2-9e45-4d41b9fb61ee");
            _menuitemlayoutInfo = new RepoItemInfo(this, "menuItemLayout", "/form/element/container/menuitem[@childindex='14']", 30000, null, "800ffd88-060f-4f18-835d-3de7fdf3e193");
            _menuitemhelpInfo = new RepoItemInfo(this, "menuItemHelp", "/container[@automationid='EnvelopeCurveModule.EnvelopeCurveForm.Form']/container[@controlname='EnvelopeCurveModule.MenuBarStub.Menubar']/element[@controlname='barDockControlTop']/element/menubar/menuitem[@childindex='1']", 30000, null, "6a96ee7b-cc29-4a4e-ac9b-1a4abc00e4b2");
            _buttonplaybackselectedcurvesInfo = new RepoItemInfo(this, "buttonPlaybackSelectedCurves", "/form[@controltypename='SubMenuControlForm']/element/container/button[@childindex='0']", 30000, null, "52124e15-b0e0-4b95-993a-2d24a17fc2d4");
            _buttonplaybackforwardInfo = new RepoItemInfo(this, "buttonPlaybackForward", "/form[@controltypename='SubMenuControlForm']/element/container/button[@childindex='1']", 30000, null, "bdc1d42e-6392-4e56-8926-68c12bc95fad");
            _buttonplaybackfastforwardInfo = new RepoItemInfo(this, "buttonPlaybackFastForward", "/form[@controltypename='SubMenuControlForm']/element/container/button[@childindex='2']", 30000, null, "09acc8f6-4a74-4f1c-860c-ed460c80caae");
            _buttonplaybackreverseInfo = new RepoItemInfo(this, "buttonPlaybackReverse", "/form[@controltypename='SubMenuControlForm']/element/container/button[@childindex='3']", 30000, null, "c2f2e305-47b1-4277-a20f-fd0e9df805b4");
            _buttonplaybackfastreverseInfo = new RepoItemInfo(this, "buttonPlaybackFastReverse", "/form[@controltypename='SubMenuControlForm']/element/container/button[@childindex='4']", 30000, null, "74d89976-e34e-4354-80c7-96d5680b94a7");
            _buttonplaybackstopInfo = new RepoItemInfo(this, "buttonPlaybackStop", "/form[@controltypename='SubMenuControlForm']/element/container/button[@childindex='5']", 30000, null, "22702648-9f68-4cf6-8744-7f076ca55eb8");
            _buttonplaybackpauseInfo = new RepoItemInfo(this, "buttonPlaybackPause", "/form[@controltypename='SubMenuControlForm']/element/container/button[@childindex='6']", 30000, null, "465e47df-904e-478f-b8c4-c0023a47a23c");
            _buttondisplayclearplotdisplayInfo = new RepoItemInfo(this, "buttonDisplayClearPlotDisplay", "/form[@controltypename='SubMenuControlForm']/element/container/button[@childindex='0']", 30000, null, "18e48438-cc3e-4694-b855-8c8fe190efdf");
            _buttondisplayzoomandgridsettingsInfo = new RepoItemInfo(this, "buttonDisplayZoomAndGridSettings", "/form[@controltypename='SubMenuControlForm']/element/container/button[@childindex='1']", 30000, null, "484dabd4-569c-4dc3-a4c5-3eeb59324148");
            _buttondisplayresetzoomareaInfo = new RepoItemInfo(this, "buttonDisplayResetZoomArea", "/form[@controltypename='SubMenuControlForm']/element/container/button[@childindex='2']", 30000, null, "e916a15f-51b9-4fc2-861f-a881c9fead36");
            _buttondisplayundozoomInfo = new RepoItemInfo(this, "buttonDisplayUndoZoom", "/form[@controltypename='SubMenuControlForm']/element/container/button[@childindex='3']", 30000, null, "f7a26c8e-bae3-449c-9c66-c8b119643d35");
            _buttondisplayfirstenvelopecurveInfo = new RepoItemInfo(this, "buttonDisplayFirstEnvelopeCurve", "/form[@controltypename='SubMenuControlForm']/element/container/button[@childindex='4']", 30000, null, "a7d332f1-e51a-44f1-9c9b-e72d2648f187");
            _buttondisplaylastenvelopecurveInfo = new RepoItemInfo(this, "buttonDisplayLastEnvelopeCurve", "/form[@controltypename='SubMenuControlForm']/element/container/button[@childindex='5']", 30000, null, "11c317c2-3b39-4a0d-ba4e-6f201811ddd5");
            _buttondisplaynextenvelopecurveInfo = new RepoItemInfo(this, "buttonDisplayNextEnvelopeCurve", "/form[@controltypename='SubMenuControlForm']/element/container/button[@childindex='6']", 30000, null, "d52de5da-cad6-4abe-9b73-d2e613325876");
            _buttondisplaypreviousenvelopecurveInfo = new RepoItemInfo(this, "buttonDisplayPreviousEnvelopeCurve", "/form[@controltypename='SubMenuControlForm']/element/container/button[@childindex='7']", 30000, null, "b6d6bb26-8742-4be9-abbb-bfec61138bbc");
            _buttonlayoutdiagramInfo = new RepoItemInfo(this, "buttonLayoutDiagram", "/form[@controltypename='SubMenuControlForm']/element/container/button[@childindex='0']", 30000, null, "d39c11e3-1e18-4c5f-b3df-47b831f54375");
            _buttonlayoutdiagramplusinfoInfo = new RepoItemInfo(this, "buttonLayoutDiagramPlusInfo", "/form[@controltypename='SubMenuControlForm']/element/container/button[@childindex='1']", 30000, null, "ccd79559-2858-4e87-8f7d-b8d77739c5a2");
            _buttonhelpcontentsInfo = new RepoItemInfo(this, "buttonHelpContents", "/form/container/container/container/container[@controlname='EnvelopeCurveModule.ToolBarStub.Toolbar']/element[@controlname='barDockControlTop']/element/toolbar/button[@childindex='0']", 30000, null, "9ce2caa6-53bf-4300-82f9-d80c171c1c57");
            _buttonhelpaboutInfo = new RepoItemInfo(this, "buttonHelpAbout", "/form/container/container/container/container[@controlname='EnvelopeCurveModule.ToolBarStub.Toolbar']/element[@controlname='barDockControlTop']/element/toolbar/button[@childindex='1']", 30000, null, "dded69fc-0aa0-4764-a2ef-a11bfda7f414");
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("3786e64d-e731-4336-8515-e5d826b8505c")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The menuItemEnvelopeCurve item.
        /// </summary>
        [RepositoryItem("3b0a8da4-de1c-4bca-9902-ddabfe053acd")]
        public virtual Ranorex.MenuItem menuItemEnvelopeCurve
        {
            get
            {
                 return _menuitemenvelopecurveInfo.CreateAdapter<Ranorex.MenuItem>(true);
            }
        }

        /// <summary>
        /// The menuItemEnvelopeCurve item info.
        /// </summary>
        [RepositoryItemInfo("3b0a8da4-de1c-4bca-9902-ddabfe053acd")]
        public virtual RepoItemInfo menuItemEnvelopeCurveInfo
        {
            get
            {
                return _menuitemenvelopecurveInfo;
            }
        }

        /// <summary>
        /// The buttonNewCurve item.
        /// </summary>
        [RepositoryItem("348ef014-fcbf-407c-bc1d-b4bac1c1d3ab")]
        public virtual Ranorex.Button buttonNewCurve
        {
            get
            {
                 return _buttonnewcurveInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonNewCurve item info.
        /// </summary>
        [RepositoryItemInfo("348ef014-fcbf-407c-bc1d-b4bac1c1d3ab")]
        public virtual RepoItemInfo buttonNewCurveInfo
        {
            get
            {
                return _buttonnewcurveInfo;
            }
        }

        /// <summary>
        /// The buttonOpenCurve item.
        /// </summary>
        [RepositoryItem("b4a5636a-8525-453a-bed2-a255da4cf419")]
        public virtual Ranorex.Button buttonOpenCurve
        {
            get
            {
                 return _buttonopencurveInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonOpenCurve item info.
        /// </summary>
        [RepositoryItemInfo("b4a5636a-8525-453a-bed2-a255da4cf419")]
        public virtual RepoItemInfo buttonOpenCurveInfo
        {
            get
            {
                return _buttonopencurveInfo;
            }
        }

        /// <summary>
        /// The buttonSaveCurve item.
        /// </summary>
        [RepositoryItem("a8c11b17-f120-43eb-9532-bcf2ae0de394")]
        public virtual Ranorex.Button buttonSaveCurve
        {
            get
            {
                 return _buttonsavecurveInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonSaveCurve item info.
        /// </summary>
        [RepositoryItemInfo("a8c11b17-f120-43eb-9532-bcf2ae0de394")]
        public virtual RepoItemInfo buttonSaveCurveInfo
        {
            get
            {
                return _buttonsavecurveInfo;
            }
        }

        /// <summary>
        /// The buttonSaveCurveAs item.
        /// </summary>
        [RepositoryItem("03da229c-40d2-4992-9847-a63f425039b9")]
        public virtual Ranorex.Button buttonSaveCurveAs
        {
            get
            {
                 return _buttonsavecurveasInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonSaveCurveAs item info.
        /// </summary>
        [RepositoryItemInfo("03da229c-40d2-4992-9847-a63f425039b9")]
        public virtual RepoItemInfo buttonSaveCurveAsInfo
        {
            get
            {
                return _buttonsavecurveasInfo;
            }
        }

        /// <summary>
        /// The elementMenuElement item.
        /// </summary>
        [RepositoryItem("7fe8bf68-6bfe-493f-9d53-32d81114d1ae")]
        public virtual Ranorex.Unknown elementMenuElement
        {
            get
            {
                 return _elementmenuelementInfo.CreateAdapter<Ranorex.Unknown>(true);
            }
        }

        /// <summary>
        /// The elementMenuElement item info.
        /// </summary>
        [RepositoryItemInfo("7fe8bf68-6bfe-493f-9d53-32d81114d1ae")]
        public virtual RepoItemInfo elementMenuElementInfo
        {
            get
            {
                return _elementmenuelementInfo;
            }
        }

        /// <summary>
        /// The containerMenuContainer item.
        /// </summary>
        [RepositoryItem("44255b92-0288-4d0e-8798-5a410727c82b")]
        public virtual Ranorex.Container containerMenuContainer
        {
            get
            {
                 return _containermenucontainerInfo.CreateAdapter<Ranorex.Container>(true);
            }
        }

        /// <summary>
        /// The containerMenuContainer item info.
        /// </summary>
        [RepositoryItemInfo("44255b92-0288-4d0e-8798-5a410727c82b")]
        public virtual RepoItemInfo containerMenuContainerInfo
        {
            get
            {
                return _containermenucontainerInfo;
            }
        }

        /// <summary>
        /// The buttonReadCurve item.
        /// </summary>
        [RepositoryItem("ed07aa80-9e8b-45ec-9f18-04b48e9a0803")]
        public virtual Ranorex.Button buttonReadCurve
        {
            get
            {
                 return _buttonreadcurveInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonReadCurve item info.
        /// </summary>
        [RepositoryItemInfo("ed07aa80-9e8b-45ec-9f18-04b48e9a0803")]
        public virtual RepoItemInfo buttonReadCurveInfo
        {
            get
            {
                return _buttonreadcurveInfo;
            }
        }

        /// <summary>
        /// The buttonCyclicRead item.
        /// </summary>
        [RepositoryItem("6769f89d-d2c5-41c4-ae49-72483101801a")]
        public virtual Ranorex.Button buttonCyclicRead
        {
            get
            {
                 return _buttoncyclicreadInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonCyclicRead item info.
        /// </summary>
        [RepositoryItemInfo("6769f89d-d2c5-41c4-ae49-72483101801a")]
        public virtual RepoItemInfo buttonCyclicReadInfo
        {
            get
            {
                return _buttoncyclicreadInfo;
            }
        }

        /// <summary>
        /// The buttonEndReadWrite item.
        /// </summary>
        [RepositoryItem("b8277938-8f12-444c-af07-67c458b001d9")]
        public virtual Ranorex.Button buttonEndReadWrite
        {
            get
            {
                 return _buttonendreadwriteInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonEndReadWrite item info.
        /// </summary>
        [RepositoryItemInfo("b8277938-8f12-444c-af07-67c458b001d9")]
        public virtual RepoItemInfo buttonEndReadWriteInfo
        {
            get
            {
                return _buttonendreadwriteInfo;
            }
        }

        /// <summary>
        /// The buttonReadSettings item.
        /// </summary>
        [RepositoryItem("1f277284-548a-4d1a-9c7b-9844c6fb0a9f")]
        public virtual Ranorex.Button buttonReadSettings
        {
            get
            {
                 return _buttonreadsettingsInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonReadSettings item info.
        /// </summary>
        [RepositoryItemInfo("1f277284-548a-4d1a-9c7b-9844c6fb0a9f")]
        public virtual RepoItemInfo buttonReadSettingsInfo
        {
            get
            {
                return _buttonreadsettingsInfo;
            }
        }

        /// <summary>
        /// The buttonCyclicReadSettings item.
        /// </summary>
        [RepositoryItem("ce5bcef4-2e8b-49a5-aca1-f13b711d579b")]
        public virtual Ranorex.Button buttonCyclicReadSettings
        {
            get
            {
                 return _buttoncyclicreadsettingsInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonCyclicReadSettings item info.
        /// </summary>
        [RepositoryItemInfo("ce5bcef4-2e8b-49a5-aca1-f13b711d579b")]
        public virtual RepoItemInfo buttonCyclicReadSettingsInfo
        {
            get
            {
                return _buttoncyclicreadsettingsInfo;
            }
        }

        /// <summary>
        /// The buttonResetReadingRange item.
        /// </summary>
        [RepositoryItem("0f6d56ca-2d6e-4356-af7f-451f27dfad1b")]
        public virtual Ranorex.Button buttonResetReadingRange
        {
            get
            {
                 return _buttonresetreadingrangeInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonResetReadingRange item info.
        /// </summary>
        [RepositoryItemInfo("0f6d56ca-2d6e-4356-af7f-451f27dfad1b")]
        public virtual RepoItemInfo buttonResetReadingRangeInfo
        {
            get
            {
                return _buttonresetreadingrangeInfo;
            }
        }

        /// <summary>
        /// The buttonOverlappedCurves item.
        /// </summary>
        [RepositoryItem("9c1a5c97-9a9a-4dc7-b44b-00ce1fa0e874")]
        public virtual Ranorex.Button buttonOverlappedCurves
        {
            get
            {
                 return _buttonoverlappedcurvesInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonOverlappedCurves item info.
        /// </summary>
        [RepositoryItemInfo("9c1a5c97-9a9a-4dc7-b44b-00ce1fa0e874")]
        public virtual RepoItemInfo buttonOverlappedCurvesInfo
        {
            get
            {
                return _buttonoverlappedcurvesInfo;
            }
        }

        /// <summary>
        /// The menuItemPlayBack item.
        /// </summary>
        [RepositoryItem("86e286ca-2db3-4b52-b2da-04273a2c88b2")]
        public virtual Ranorex.MenuItem menuItemPlayBack
        {
            get
            {
                 return _menuitemplaybackInfo.CreateAdapter<Ranorex.MenuItem>(true);
            }
        }

        /// <summary>
        /// The menuItemPlayBack item info.
        /// </summary>
        [RepositoryItemInfo("86e286ca-2db3-4b52-b2da-04273a2c88b2")]
        public virtual RepoItemInfo menuItemPlayBackInfo
        {
            get
            {
                return _menuitemplaybackInfo;
            }
        }

        /// <summary>
        /// The menuItemDisplay item.
        /// </summary>
        [RepositoryItem("0e2aa8fc-d00e-457b-81f0-e83a505ceff4")]
        public virtual Ranorex.MenuItem menuItemDisplay
        {
            get
            {
                 return _menuitemdisplayInfo.CreateAdapter<Ranorex.MenuItem>(true);
            }
        }

        /// <summary>
        /// The menuItemDisplay item info.
        /// </summary>
        [RepositoryItemInfo("0e2aa8fc-d00e-457b-81f0-e83a505ceff4")]
        public virtual RepoItemInfo menuItemDisplayInfo
        {
            get
            {
                return _menuitemdisplayInfo;
            }
        }

        /// <summary>
        /// The buttonRemarks item.
        /// </summary>
        [RepositoryItem("1ea30c6e-7b6d-46a2-9e45-4d41b9fb61ee")]
        public virtual Ranorex.Button buttonRemarks
        {
            get
            {
                 return _buttonremarksInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonRemarks item info.
        /// </summary>
        [RepositoryItemInfo("1ea30c6e-7b6d-46a2-9e45-4d41b9fb61ee")]
        public virtual RepoItemInfo buttonRemarksInfo
        {
            get
            {
                return _buttonremarksInfo;
            }
        }

        /// <summary>
        /// The menuItemLayout item.
        /// </summary>
        [RepositoryItem("800ffd88-060f-4f18-835d-3de7fdf3e193")]
        public virtual Ranorex.MenuItem menuItemLayout
        {
            get
            {
                 return _menuitemlayoutInfo.CreateAdapter<Ranorex.MenuItem>(true);
            }
        }

        /// <summary>
        /// The menuItemLayout item info.
        /// </summary>
        [RepositoryItemInfo("800ffd88-060f-4f18-835d-3de7fdf3e193")]
        public virtual RepoItemInfo menuItemLayoutInfo
        {
            get
            {
                return _menuitemlayoutInfo;
            }
        }

        /// <summary>
        /// The menuItemHelp item.
        /// </summary>
        [RepositoryItem("6a96ee7b-cc29-4a4e-ac9b-1a4abc00e4b2")]
        public virtual Ranorex.MenuItem menuItemHelp
        {
            get
            {
                 return _menuitemhelpInfo.CreateAdapter<Ranorex.MenuItem>(true);
            }
        }

        /// <summary>
        /// The menuItemHelp item info.
        /// </summary>
        [RepositoryItemInfo("6a96ee7b-cc29-4a4e-ac9b-1a4abc00e4b2")]
        public virtual RepoItemInfo menuItemHelpInfo
        {
            get
            {
                return _menuitemhelpInfo;
            }
        }

        /// <summary>
        /// The buttonPlaybackSelectedCurves item.
        /// </summary>
        [RepositoryItem("52124e15-b0e0-4b95-993a-2d24a17fc2d4")]
        public virtual Ranorex.Button buttonPlaybackSelectedCurves
        {
            get
            {
                 return _buttonplaybackselectedcurvesInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonPlaybackSelectedCurves item info.
        /// </summary>
        [RepositoryItemInfo("52124e15-b0e0-4b95-993a-2d24a17fc2d4")]
        public virtual RepoItemInfo buttonPlaybackSelectedCurvesInfo
        {
            get
            {
                return _buttonplaybackselectedcurvesInfo;
            }
        }

        /// <summary>
        /// The buttonPlaybackForward item.
        /// </summary>
        [RepositoryItem("bdc1d42e-6392-4e56-8926-68c12bc95fad")]
        public virtual Ranorex.Button buttonPlaybackForward
        {
            get
            {
                 return _buttonplaybackforwardInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonPlaybackForward item info.
        /// </summary>
        [RepositoryItemInfo("bdc1d42e-6392-4e56-8926-68c12bc95fad")]
        public virtual RepoItemInfo buttonPlaybackForwardInfo
        {
            get
            {
                return _buttonplaybackforwardInfo;
            }
        }

        /// <summary>
        /// The buttonPlaybackFastForward item.
        /// </summary>
        [RepositoryItem("09acc8f6-4a74-4f1c-860c-ed460c80caae")]
        public virtual Ranorex.Button buttonPlaybackFastForward
        {
            get
            {
                 return _buttonplaybackfastforwardInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonPlaybackFastForward item info.
        /// </summary>
        [RepositoryItemInfo("09acc8f6-4a74-4f1c-860c-ed460c80caae")]
        public virtual RepoItemInfo buttonPlaybackFastForwardInfo
        {
            get
            {
                return _buttonplaybackfastforwardInfo;
            }
        }

        /// <summary>
        /// The buttonPlaybackReverse item.
        /// </summary>
        [RepositoryItem("c2f2e305-47b1-4277-a20f-fd0e9df805b4")]
        public virtual Ranorex.Button buttonPlaybackReverse
        {
            get
            {
                 return _buttonplaybackreverseInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonPlaybackReverse item info.
        /// </summary>
        [RepositoryItemInfo("c2f2e305-47b1-4277-a20f-fd0e9df805b4")]
        public virtual RepoItemInfo buttonPlaybackReverseInfo
        {
            get
            {
                return _buttonplaybackreverseInfo;
            }
        }

        /// <summary>
        /// The buttonPlaybackFastReverse item.
        /// </summary>
        [RepositoryItem("74d89976-e34e-4354-80c7-96d5680b94a7")]
        public virtual Ranorex.Button buttonPlaybackFastReverse
        {
            get
            {
                 return _buttonplaybackfastreverseInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonPlaybackFastReverse item info.
        /// </summary>
        [RepositoryItemInfo("74d89976-e34e-4354-80c7-96d5680b94a7")]
        public virtual RepoItemInfo buttonPlaybackFastReverseInfo
        {
            get
            {
                return _buttonplaybackfastreverseInfo;
            }
        }

        /// <summary>
        /// The buttonPlaybackStop item.
        /// </summary>
        [RepositoryItem("22702648-9f68-4cf6-8744-7f076ca55eb8")]
        public virtual Ranorex.Button buttonPlaybackStop
        {
            get
            {
                 return _buttonplaybackstopInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonPlaybackStop item info.
        /// </summary>
        [RepositoryItemInfo("22702648-9f68-4cf6-8744-7f076ca55eb8")]
        public virtual RepoItemInfo buttonPlaybackStopInfo
        {
            get
            {
                return _buttonplaybackstopInfo;
            }
        }

        /// <summary>
        /// The buttonPlaybackPause item.
        /// </summary>
        [RepositoryItem("465e47df-904e-478f-b8c4-c0023a47a23c")]
        public virtual Ranorex.Button buttonPlaybackPause
        {
            get
            {
                 return _buttonplaybackpauseInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonPlaybackPause item info.
        /// </summary>
        [RepositoryItemInfo("465e47df-904e-478f-b8c4-c0023a47a23c")]
        public virtual RepoItemInfo buttonPlaybackPauseInfo
        {
            get
            {
                return _buttonplaybackpauseInfo;
            }
        }

        /// <summary>
        /// The buttonDisplayClearPlotDisplay item.
        /// </summary>
        [RepositoryItem("18e48438-cc3e-4694-b855-8c8fe190efdf")]
        public virtual Ranorex.Button buttonDisplayClearPlotDisplay
        {
            get
            {
                 return _buttondisplayclearplotdisplayInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonDisplayClearPlotDisplay item info.
        /// </summary>
        [RepositoryItemInfo("18e48438-cc3e-4694-b855-8c8fe190efdf")]
        public virtual RepoItemInfo buttonDisplayClearPlotDisplayInfo
        {
            get
            {
                return _buttondisplayclearplotdisplayInfo;
            }
        }

        /// <summary>
        /// The buttonDisplayZoomAndGridSettings item.
        /// </summary>
        [RepositoryItem("484dabd4-569c-4dc3-a4c5-3eeb59324148")]
        public virtual Ranorex.Button buttonDisplayZoomAndGridSettings
        {
            get
            {
                 return _buttondisplayzoomandgridsettingsInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonDisplayZoomAndGridSettings item info.
        /// </summary>
        [RepositoryItemInfo("484dabd4-569c-4dc3-a4c5-3eeb59324148")]
        public virtual RepoItemInfo buttonDisplayZoomAndGridSettingsInfo
        {
            get
            {
                return _buttondisplayzoomandgridsettingsInfo;
            }
        }

        /// <summary>
        /// The buttonDisplayResetZoomArea item.
        /// </summary>
        [RepositoryItem("e916a15f-51b9-4fc2-861f-a881c9fead36")]
        public virtual Ranorex.Button buttonDisplayResetZoomArea
        {
            get
            {
                 return _buttondisplayresetzoomareaInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonDisplayResetZoomArea item info.
        /// </summary>
        [RepositoryItemInfo("e916a15f-51b9-4fc2-861f-a881c9fead36")]
        public virtual RepoItemInfo buttonDisplayResetZoomAreaInfo
        {
            get
            {
                return _buttondisplayresetzoomareaInfo;
            }
        }

        /// <summary>
        /// The buttonDisplayUndoZoom item.
        /// </summary>
        [RepositoryItem("f7a26c8e-bae3-449c-9c66-c8b119643d35")]
        public virtual Ranorex.Button buttonDisplayUndoZoom
        {
            get
            {
                 return _buttondisplayundozoomInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonDisplayUndoZoom item info.
        /// </summary>
        [RepositoryItemInfo("f7a26c8e-bae3-449c-9c66-c8b119643d35")]
        public virtual RepoItemInfo buttonDisplayUndoZoomInfo
        {
            get
            {
                return _buttondisplayundozoomInfo;
            }
        }

        /// <summary>
        /// The buttonDisplayFirstEnvelopeCurve item.
        /// </summary>
        [RepositoryItem("a7d332f1-e51a-44f1-9c9b-e72d2648f187")]
        public virtual Ranorex.Button buttonDisplayFirstEnvelopeCurve
        {
            get
            {
                 return _buttondisplayfirstenvelopecurveInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonDisplayFirstEnvelopeCurve item info.
        /// </summary>
        [RepositoryItemInfo("a7d332f1-e51a-44f1-9c9b-e72d2648f187")]
        public virtual RepoItemInfo buttonDisplayFirstEnvelopeCurveInfo
        {
            get
            {
                return _buttondisplayfirstenvelopecurveInfo;
            }
        }

        /// <summary>
        /// The buttonDisplayLastEnvelopeCurve item.
        /// </summary>
        [RepositoryItem("11c317c2-3b39-4a0d-ba4e-6f201811ddd5")]
        public virtual Ranorex.Button buttonDisplayLastEnvelopeCurve
        {
            get
            {
                 return _buttondisplaylastenvelopecurveInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonDisplayLastEnvelopeCurve item info.
        /// </summary>
        [RepositoryItemInfo("11c317c2-3b39-4a0d-ba4e-6f201811ddd5")]
        public virtual RepoItemInfo buttonDisplayLastEnvelopeCurveInfo
        {
            get
            {
                return _buttondisplaylastenvelopecurveInfo;
            }
        }

        /// <summary>
        /// The buttonDisplayNextEnvelopeCurve item.
        /// </summary>
        [RepositoryItem("d52de5da-cad6-4abe-9b73-d2e613325876")]
        public virtual Ranorex.Button buttonDisplayNextEnvelopeCurve
        {
            get
            {
                 return _buttondisplaynextenvelopecurveInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonDisplayNextEnvelopeCurve item info.
        /// </summary>
        [RepositoryItemInfo("d52de5da-cad6-4abe-9b73-d2e613325876")]
        public virtual RepoItemInfo buttonDisplayNextEnvelopeCurveInfo
        {
            get
            {
                return _buttondisplaynextenvelopecurveInfo;
            }
        }

        /// <summary>
        /// The buttonDisplayPreviousEnvelopeCurve item.
        /// </summary>
        [RepositoryItem("b6d6bb26-8742-4be9-abbb-bfec61138bbc")]
        public virtual Ranorex.Button buttonDisplayPreviousEnvelopeCurve
        {
            get
            {
                 return _buttondisplaypreviousenvelopecurveInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonDisplayPreviousEnvelopeCurve item info.
        /// </summary>
        [RepositoryItemInfo("b6d6bb26-8742-4be9-abbb-bfec61138bbc")]
        public virtual RepoItemInfo buttonDisplayPreviousEnvelopeCurveInfo
        {
            get
            {
                return _buttondisplaypreviousenvelopecurveInfo;
            }
        }

        /// <summary>
        /// The buttonLayoutDiagram item.
        /// </summary>
        [RepositoryItem("d39c11e3-1e18-4c5f-b3df-47b831f54375")]
        public virtual Ranorex.Button buttonLayoutDiagram
        {
            get
            {
                 return _buttonlayoutdiagramInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonLayoutDiagram item info.
        /// </summary>
        [RepositoryItemInfo("d39c11e3-1e18-4c5f-b3df-47b831f54375")]
        public virtual RepoItemInfo buttonLayoutDiagramInfo
        {
            get
            {
                return _buttonlayoutdiagramInfo;
            }
        }

        /// <summary>
        /// The buttonLayoutDiagramPlusInfo item.
        /// </summary>
        [RepositoryItem("ccd79559-2858-4e87-8f7d-b8d77739c5a2")]
        public virtual Ranorex.Button buttonLayoutDiagramPlusInfo
        {
            get
            {
                 return _buttonlayoutdiagramplusinfoInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonLayoutDiagramPlusInfo item info.
        /// </summary>
        [RepositoryItemInfo("ccd79559-2858-4e87-8f7d-b8d77739c5a2")]
        public virtual RepoItemInfo buttonLayoutDiagramPlusInfoInfo
        {
            get
            {
                return _buttonlayoutdiagramplusinfoInfo;
            }
        }

        /// <summary>
        /// The buttonHelpContents item.
        /// </summary>
        [RepositoryItem("9ce2caa6-53bf-4300-82f9-d80c171c1c57")]
        public virtual Ranorex.Button buttonHelpContents
        {
            get
            {
                 return _buttonhelpcontentsInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonHelpContents item info.
        /// </summary>
        [RepositoryItemInfo("9ce2caa6-53bf-4300-82f9-d80c171c1c57")]
        public virtual RepoItemInfo buttonHelpContentsInfo
        {
            get
            {
                return _buttonhelpcontentsInfo;
            }
        }

        /// <summary>
        /// The buttonHelpAbout item.
        /// </summary>
        [RepositoryItem("dded69fc-0aa0-4764-a2ef-a11bfda7f414")]
        public virtual Ranorex.Button buttonHelpAbout
        {
            get
            {
                 return _buttonhelpaboutInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonHelpAbout item info.
        /// </summary>
        [RepositoryItemInfo("dded69fc-0aa0-4764-a2ef-a11bfda7f414")]
        public virtual RepoItemInfo buttonHelpAboutInfo
        {
            get
            {
                return _buttonhelpaboutInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    public partial class ElementsRepositoryFolders
    {
    }
#pragma warning restore 0436
}