using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ReviewBoardVsx.Ids
{
    /// <summary>
    /// These Package Load Key settings are required for VS 2008 and earlier.
    /// If any of the below values change then a new PLK will need to be requested from:
    /// http://msdn.microsoft.com/en-us/vstudio/cc655795
    /// The PLK generated by Microsoft must then be updated in VSPackage.resx.
    /// </summary>
    public static class MyPackageLoadKey
    {
        public const string PackageId = "bbffe0ea-3383-4ea2-a281-528706f79d57";
        public const string MinimumVsEdition = "Standard";
        public const string Version = "1.0";
        public const string Product = "ReviewBoardVsx";
        public const string Company = "reviewboard.org";
        public const int KeyResourceId = 1; // resource id of PLK in VSPackage.resx (mandatory file for VS Packages)
    }

    public static class MyPackageConstants
    {
        public const string PackageDescription = MyPackageLoadKey.Product + " - ReviewBoard Extension for Visual Studio";

        //**********************************************************************************
        public const string AssemblyCopyright = "Copyright © " + MyPackageLoadKey.Company + " 2011";
        public const string AssemblyProduct = PackageDescription;
        public const string AssemblyCompany = MyPackageLoadKey.Company;

        //**********************************************************************************
        // Items for the VS 2010 Extension registration
        public const string ExtensionTitle = AssemblyProduct;
        public const string ExtensionAuthor = AssemblyCompany;
        public const string ExtensionDescription = "ReviewBoard Extension for Visual Studio";
        public const string ExtensionMoreInfoUrl = "http://www.reviewboard.org";
        public const string ExtensionGettingStartedUrl = "http://www.reviewboard.org";

        //**********************************************************************************
        // Required guids for the menu item(s) used by this package
        public const string CommandGroupId = "ed66aa69-7606-4fe2-852f-ecda6208097d";
        public const string CommandSetId = "d98ce002-7ba4-42ec-83d6-08492024ec22";

        //public static readonly Guid PackageIdGuid = new Guid(PackageLoadKey.PackageId);
        //public static readonly Guid CommandGroupIdGuid = new Guid(CommandGroupId);
        public static readonly Guid CommandSetIdGuid = new Guid(CommandSetId);
    }

    public static class MyPackageCommandIds
    {
        public const int cmdIdReviewBoard = 0x100;
    }

    public static class MyVsConstants
    {
        /// <summary>
        /// Found in "%ProgramFiles(x86)%\Microsoft Visual Studio 2008 SDK\VisualStudioIntegration\Common\inc\vsshlids.h"
        /// </summary>
        public const string UICONTEXT_SolutionExists = "f1536ef8-92ec-443c-9ed7-fdadf150da82";
    }
}
