///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace EH.PCPS.TestAutomation.FFH1CommDTM.V1542.GUI
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the FFH1CommDTMRepo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    [RepositoryFolder("303038cf-4df5-4435-b19f-92b4adb64693")]
    public partial class FFH1CommDTMRepo : RepoGenBaseFolder
    {
        static FFH1CommDTMRepo instance = new FFH1CommDTMRepo();
        FFH1CommDTMRepoFolders.ApplicationAreaFolder _applicationarea;
        FFH1CommDTMRepoFolders.CommDTMDialogAppFolder _commdtmdialog;
        FFH1CommDTMRepoFolders.List1000AppFolder _list1000;
        FFH1CommDTMRepoFolders.MDIParent2AppFolder _mdiparent2;

        /// <summary>
        /// Gets the singleton class instance representing the FFH1CommDTMRepo element repository.
        /// </summary>
        [RepositoryFolder("303038cf-4df5-4435-b19f-92b4adb64693")]
        public static FFH1CommDTMRepo Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public FFH1CommDTMRepo() 
            : base("FFH1CommDTMRepo", "/", null, 0, false, "303038cf-4df5-4435-b19f-92b4adb64693", ".\\RepositoryImages\\FFH1CommDTMRepo303038cf.rximgres")
        {
            _applicationarea = new FFH1CommDTMRepoFolders.ApplicationAreaFolder(this);
            _commdtmdialog = new FFH1CommDTMRepoFolders.CommDTMDialogAppFolder(this);
            _list1000 = new FFH1CommDTMRepoFolders.List1000AppFolder(this);
            _mdiparent2 = new FFH1CommDTMRepoFolders.MDIParent2AppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("303038cf-4df5-4435-b19f-92b4adb64693")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationArea folder.
        /// </summary>
        [RepositoryFolder("8a59b978-c1ee-49e7-b640-2a6f87e1c841")]
        public virtual FFH1CommDTMRepoFolders.ApplicationAreaFolder ApplicationArea
        {
            get { return _applicationarea; }
        }

        /// <summary>
        /// The CommDTMDialog folder.
        /// </summary>
        [RepositoryFolder("7d1a928a-4aa6-4846-8f46-4c685d2faeb1")]
        public virtual FFH1CommDTMRepoFolders.CommDTMDialogAppFolder CommDTMDialog
        {
            get { return _commdtmdialog; }
        }

        /// <summary>
        /// The List1000 folder.
        /// </summary>
        [RepositoryFolder("790a840d-7ffe-4740-944e-050cd84723c1")]
        public virtual FFH1CommDTMRepoFolders.List1000AppFolder List1000
        {
            get { return _list1000; }
        }

        /// <summary>
        /// The MDIParent2 folder.
        /// </summary>
        [RepositoryFolder("db611aed-c0b1-4042-a657-a8750fdd4d73")]
        public virtual FFH1CommDTMRepoFolders.MDIParent2AppFolder MDIParent2
        {
            get { return _mdiparent2; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    public partial class FFH1CommDTMRepoFolders
    {
        /// <summary>
        /// The ApplicationAreaFolder folder.
        /// </summary>
        [RepositoryFolder("8a59b978-c1ee-49e7-b640-2a6f87e1c841")]
        public partial class ApplicationAreaFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttoncancelInfo;
            RepoItemInfo _buttonokInfo;
            RepoItemInfo _linknamecomboboxInfo;
            RepoItemInfo _linknamecomboboxbuttonopenInfo;

            /// <summary>
            /// Creates a new ApplicationArea  folder.
            /// </summary>
            public ApplicationAreaFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationArea", "", parentFolder, 0, null, false, "8a59b978-c1ee-49e7-b640-2a6f87e1c841", "")
            {
                _buttoncancelInfo = new RepoItemInfo(this, "ButtonCancel", "/button[@text='Cancel' and @class='Button']", 30000, null, "f19990fa-8030-490c-9ce2-6d7257d09dc6");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "/button[@text='OK' and @class='Button']", 30000, null, "085df970-c566-4f8a-b897-2b0254b45dfa");
                _linknamecomboboxInfo = new RepoItemInfo(this, "LinkNameCombobox", "/combobox[@class='ComboBox' and @instance='0']", 30000, null, "c441d061-54b9-4e16-9122-a7425830dc31");
                _linknamecomboboxbuttonopenInfo = new RepoItemInfo(this, "LinkNameComboboxButtonOpen", "/combobox[@class='ComboBox' and @instance='0']/button[@text='>']", 30000, null, "6473ccc2-d3b1-4a3d-84c6-9611fcab81b0");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8a59b978-c1ee-49e7-b640-2a6f87e1c841")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonCancel item.
            /// </summary>
            [RepositoryItem("f19990fa-8030-490c-9ce2-6d7257d09dc6")]
            public virtual Ranorex.Button ButtonCancel
            {
                get
                {
                    return _buttoncancelInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonCancel item info.
            /// </summary>
            [RepositoryItemInfo("f19990fa-8030-490c-9ce2-6d7257d09dc6")]
            public virtual RepoItemInfo ButtonCancelInfo
            {
                get
                {
                    return _buttoncancelInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("085df970-c566-4f8a-b897-2b0254b45dfa")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("085df970-c566-4f8a-b897-2b0254b45dfa")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }

            /// <summary>
            /// The LinkNameCombobox item.
            /// </summary>
            [RepositoryItem("c441d061-54b9-4e16-9122-a7425830dc31")]
            public virtual Ranorex.ComboBox LinkNameCombobox
            {
                get
                {
                    return _linknamecomboboxInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The LinkNameCombobox item info.
            /// </summary>
            [RepositoryItemInfo("c441d061-54b9-4e16-9122-a7425830dc31")]
            public virtual RepoItemInfo LinkNameComboboxInfo
            {
                get
                {
                    return _linknamecomboboxInfo;
                }
            }

            /// <summary>
            /// The LinkNameComboboxButtonOpen item.
            /// </summary>
            [RepositoryItem("6473ccc2-d3b1-4a3d-84c6-9611fcab81b0")]
            public virtual Ranorex.Button LinkNameComboboxButtonOpen
            {
                get
                {
                    return _linknamecomboboxbuttonopenInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The LinkNameComboboxButtonOpen item info.
            /// </summary>
            [RepositoryItemInfo("6473ccc2-d3b1-4a3d-84c6-9611fcab81b0")]
            public virtual RepoItemInfo LinkNameComboboxButtonOpenInfo
            {
                get
                {
                    return _linknamecomboboxbuttonopenInfo;
                }
            }
        }

        /// <summary>
        /// The CommDTMDialogAppFolder folder.
        /// </summary>
        [RepositoryFolder("7d1a928a-4aa6-4846-8f46-4c685d2faeb1")]
        public partial class CommDTMDialogAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonokInfo;
            RepoItemInfo _buttoncloseInfo;
            RepoItemInfo _dialogmessageInfo;

            /// <summary>
            /// Creates a new CommDTMDialog  folder.
            /// </summary>
            public CommDTMDialogAppFolder(RepoGenBaseFolder parentFolder) :
                    base("CommDTMDialog", "/form[@title~'^FF\\ H1\\ CommDTM\\ \\[FF\\ H1\\ Comm' and @processname='FMPFrame' and @class='#32770']", parentFolder, 30000, null, true, "7d1a928a-4aa6-4846-8f46-4c685d2faeb1", "")
            {
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "button[@text='OK' and @class='Button']", 30000, null, "fdfa1c77-18cc-4f19-b322-787865418be0");
                _buttoncloseInfo = new RepoItemInfo(this, "ButtonClose", "titlebar[@accessiblerole='TitleBar' and @accessibledescription~'^Displays\\ the\\ name\\ of\\ the\\ ' and @text~'^FF\\ H1\\ CommDTM\\ \\[FF\\ H1\\ Comm']/button[@accessiblename='Close' and @accessiblerole='PushButton' and @text='Close']", 30000, null, "fd13c7c0-0a0f-4d96-894e-b380c91f3a31");
                _dialogmessageInfo = new RepoItemInfo(this, "DialogMessage", "text[@class='RICHEDIT' and @instance='0']", 30000, null, "754ea3e0-ac99-4f4b-a336-c9d75bdf6ee2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7d1a928a-4aa6-4846-8f46-4c685d2faeb1")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7d1a928a-4aa6-4846-8f46-4c685d2faeb1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("fdfa1c77-18cc-4f19-b322-787865418be0")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("fdfa1c77-18cc-4f19-b322-787865418be0")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }

            /// <summary>
            /// The ButtonClose item.
            /// </summary>
            [RepositoryItem("fd13c7c0-0a0f-4d96-894e-b380c91f3a31")]
            public virtual Ranorex.Button ButtonClose
            {
                get
                {
                    return _buttoncloseInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonClose item info.
            /// </summary>
            [RepositoryItemInfo("fd13c7c0-0a0f-4d96-894e-b380c91f3a31")]
            public virtual RepoItemInfo ButtonCloseInfo
            {
                get
                {
                    return _buttoncloseInfo;
                }
            }

            /// <summary>
            /// The DialogMessage item.
            /// </summary>
            [RepositoryItem("754ea3e0-ac99-4f4b-a336-c9d75bdf6ee2")]
            public virtual Ranorex.Text DialogMessage
            {
                get
                {
                    return _dialogmessageInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The DialogMessage item info.
            /// </summary>
            [RepositoryItemInfo("754ea3e0-ac99-4f4b-a336-c9d75bdf6ee2")]
            public virtual RepoItemInfo DialogMessageInfo
            {
                get
                {
                    return _dialogmessageInfo;
                }
            }
        }

        /// <summary>
        /// The List1000AppFolder folder.
        /// </summary>
        [RepositoryFolder("790a840d-7ffe-4740-944e-050cd84723c1")]
        public partial class List1000AppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new List1000  folder.
            /// </summary>
            public List1000AppFolder(RepoGenBaseFolder parentFolder) :
                    base("List1000", "/list[@processname='FMPFrame' and @class='ComboLBox']", parentFolder, 30000, null, true, "790a840d-7ffe-4740-944e-050cd84723c1", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("790a840d-7ffe-4740-944e-050cd84723c1")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("790a840d-7ffe-4740-944e-050cd84723c1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The MDIParent2AppFolder folder.
        /// </summary>
        [RepositoryFolder("db611aed-c0b1-4042-a657-a8750fdd4d73")]
        public partial class MDIParent2AppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new MDIParent2  folder.
            /// </summary>
            public MDIParent2AppFolder(RepoGenBaseFolder parentFolder) :
                    base("MDIParent2", "/form[@controlname='MDIParent2' and @title~'^FieldCare\\ -\\ Professional\\ ' and @processname='FMPFrame']", parentFolder, 30000, null, true, "db611aed-c0b1-4042-a657-a8750fdd4d73", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("db611aed-c0b1-4042-a657-a8750fdd4d73")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("db611aed-c0b1-4042-a657-a8750fdd4d73")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}