///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace EH.PCPS.TestAutomation.TestPackageUpdateA2017.Parameterization.GUI.ApplicationArea.MainView
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the DashboardElementsRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    [RepositoryFolder("33d4422e-b317-4152-aa8b-0f40bdfbf743")]
    public partial class DashboardElementsRepository : RepoGenBaseFolder
    {
        static DashboardElementsRepository instance = new DashboardElementsRepository();
        DashboardElementsRepositoryFolders.DashboardFolder _dashboard;
        DashboardElementsRepositoryFolders.ExtendedFolder _extended;
        RepoItemInfo _elementtabcontrolInfo;
        RepoItemInfo _containerprocessvariablespanelcontrolInfo;
        RepoItemInfo _homebuttonInfo;

        /// <summary>
        /// Gets the singleton class instance representing the DashboardElementsRepository element repository.
        /// </summary>
        [RepositoryFolder("33d4422e-b317-4152-aa8b-0f40bdfbf743")]
        public static DashboardElementsRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public DashboardElementsRepository() 
            : base("DashboardElementsRepository", "/", null, 0, false, "33d4422e-b317-4152-aa8b-0f40bdfbf743", ".\\RepositoryImages\\DashboardElementsRepository33d4422e.rximgres")
        {
            _dashboard = new DashboardElementsRepositoryFolders.DashboardFolder(this);
            _extended = new DashboardElementsRepositoryFolders.ExtendedFolder(this);
            _elementtabcontrolInfo = new RepoItemInfo(this, "ElementTabControl", "/container[@controltypename='DtmUserInterface']/container[@controlname='DtmDisplayArea']/?/?/container/container[@controlname='EddMenuTabPage_MenuPanel']/container[@controlname='EddMenuPanel_ScrollContainer']/container[@controlname='EddMenuPanel_ScrollContainer_ZeroLayoutContainer']//container/container[@controlname='EddMenuGroupBox_MenuPanel']//element[@controlname='TabControl']", 30000, null, "cffa1a04-a731-4e37-bdcf-ba2471e8d90d");
            _containerprocessvariablespanelcontrolInfo = new RepoItemInfo(this, "ContainerProcessVariablesPanelControl", "/container[@controltypename='DtmUserInterface']/container[@controlname='DtmDisplayArea']/?/?/container/container[@controlname='EddMenuTabPage_MenuPanel']/container[@controlname='EddMenuPanel_ScrollContainer']/container[@controlname='EddMenuPanel_ScrollContainer_ZeroLayoutContainer']//container/container[@controlname='EddMenuGroupBox_MenuPanel']/?/?/container[@controlname='GuiDashboardProcessVariablesPanelControl']", 30000, null, "04f4d013-53b0-4539-9647-86292fc9c2d7");
            _homebuttonInfo = new RepoItemInfo(this, "HomeButton", "/container[@controltypename='DtmUserInterface']/container[@controlname='DtmToolBar']/element/element/toolbar/button[@accessiblename='Go to home location.']", 30000, null, "aab60908-401e-45e3-949c-6e3368d2c041");
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("33d4422e-b317-4152-aa8b-0f40bdfbf743")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ElementTabControl item.
        /// </summary>
        [RepositoryItem("cffa1a04-a731-4e37-bdcf-ba2471e8d90d")]
        public virtual Ranorex.Unknown ElementTabControl
        {
            get
            {
                 return _elementtabcontrolInfo.CreateAdapter<Ranorex.Unknown>(true);
            }
        }

        /// <summary>
        /// The ElementTabControl item info.
        /// </summary>
        [RepositoryItemInfo("cffa1a04-a731-4e37-bdcf-ba2471e8d90d")]
        public virtual RepoItemInfo ElementTabControlInfo
        {
            get
            {
                return _elementtabcontrolInfo;
            }
        }

        /// <summary>
        /// The ContainerProcessVariablesPanelControl item.
        /// </summary>
        [RepositoryItem("04f4d013-53b0-4539-9647-86292fc9c2d7")]
        public virtual Ranorex.Container ContainerProcessVariablesPanelControl
        {
            get
            {
                 return _containerprocessvariablespanelcontrolInfo.CreateAdapter<Ranorex.Container>(true);
            }
        }

        /// <summary>
        /// The ContainerProcessVariablesPanelControl item info.
        /// </summary>
        [RepositoryItemInfo("04f4d013-53b0-4539-9647-86292fc9c2d7")]
        public virtual RepoItemInfo ContainerProcessVariablesPanelControlInfo
        {
            get
            {
                return _containerprocessvariablespanelcontrolInfo;
            }
        }

        /// <summary>
        /// The HomeButton item.
        /// </summary>
        [RepositoryItem("aab60908-401e-45e3-949c-6e3368d2c041")]
        public virtual Ranorex.Button HomeButton
        {
            get
            {
                 return _homebuttonInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The HomeButton item info.
        /// </summary>
        [RepositoryItemInfo("aab60908-401e-45e3-949c-6e3368d2c041")]
        public virtual RepoItemInfo HomeButtonInfo
        {
            get
            {
                return _homebuttonInfo;
            }
        }

        /// <summary>
        /// The Dashboard folder.
        /// </summary>
        [RepositoryFolder("52aede55-fa4d-411a-9152-c974251dfba1")]
        public virtual DashboardElementsRepositoryFolders.DashboardFolder Dashboard
        {
            get { return _dashboard; }
        }

        /// <summary>
        /// The Extended folder.
        /// </summary>
        [RepositoryFolder("77e17510-d82d-4562-811f-8ccf278b46bd")]
        public virtual DashboardElementsRepositoryFolders.ExtendedFolder Extended
        {
            get { return _extended; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    public partial class DashboardElementsRepositoryFolders
    {
        /// <summary>
        /// The DashboardFolder folder.
        /// </summary>
        [RepositoryFolder("52aede55-fa4d-411a-9152-c974251dfba1")]
        public partial class DashboardFolder : RepoGenBaseFolder
        {
            RepoItemInfo _containermainlabelInfo;
            RepoItemInfo _containeralternatemeasuredvaluelabel1Info;
            RepoItemInfo _containeralternatemeasuredvaluelabel2Info;
            RepoItemInfo _containeralternatemeasuredvaluelabel3Info;
            RepoItemInfo _containeralternatemeasuredvaluelabel4Info;

            /// <summary>
            /// Creates a new Dashboard  folder.
            /// </summary>
            public DashboardFolder(RepoGenBaseFolder parentFolder) :
                    base("Dashboard", "", parentFolder, 0, null, false, "52aede55-fa4d-411a-9152-c974251dfba1", "")
            {
                _containermainlabelInfo = new RepoItemInfo(this, "ContainerMainLabel", "/container[@controltypename='DtmUserInterface']/container[@controlname='DtmDisplayArea']/?/?/container[@controlname~'TabPage_Menu_Root_DiagnosticPage']/container[@controlname='EddMenuTabPage_MenuPanel']/container[@controlname='EddMenuPanel_ScrollContainer']/container[@controlname='EddMenuPanel_ScrollContainer_ZeroLayoutContainer']//container[@controlname~'NE107_header_DiagnosticGraph']/container[@controlname='EddMenuGroupBox_MenuPanel']//container[@controltypename='DtmPluginHost']/container[@controlname='GuiDashboardProcessVariablesPanelControl']/container[@controlname='MainDashboardPanel']/?/?/container[@controlname='label']", 30000, null, "ee2b815b-287b-4997-b9ac-3b348f377cca");
                _containeralternatemeasuredvaluelabel1Info = new RepoItemInfo(this, "ContainerAlternateMeasuredValueLabel1", "/container[@controltypename='DtmUserInterface']/container[@controlname='DtmDisplayArea']/?/?/container[@controlname~'TabPage_Menu_Root_DiagnosticPage']/container[@controlname='EddMenuTabPage_MenuPanel']/container[@controlname='EddMenuPanel_ScrollContainer']/container[@controlname='EddMenuPanel_ScrollContainer_ZeroLayoutContainer']//container[@controlname~'NE107_header_DiagnosticGraph']/container[@controlname='EddMenuGroupBox_MenuPanel']//container[@controltypename='DtmPluginHost']/container[@controlname='GuiDashboardProcessVariablesPanelControl']/container[@controlname='MainDashboardPanel']/?/?/container[@controlname='alternateMeasuredValueLabel1']", 30000, null, "a1ab5820-9896-46ad-bbd0-6189d5b203a9");
                _containeralternatemeasuredvaluelabel2Info = new RepoItemInfo(this, "ContainerAlternateMeasuredValueLabel2", "/container[@controltypename='DtmUserInterface']/container[@controlname='DtmDisplayArea']/?/?/container[@controlname~'TabPage_Menu_Root_DiagnosticPage']/container[@controlname='EddMenuTabPage_MenuPanel']/container[@controlname='EddMenuPanel_ScrollContainer']/container[@controlname='EddMenuPanel_ScrollContainer_ZeroLayoutContainer']//container[@controlname~'NE107_header_DiagnosticGraph']/container[@controlname='EddMenuGroupBox_MenuPanel']//container[@controltypename='DtmPluginHost']/container[@controlname='GuiDashboardProcessVariablesPanelControl']/container[@controlname='MainDashboardPanel']/?/?/container[@controlname='alternateMeasuredValueLabel2']", 30000, null, "8561b1a9-053f-4287-9b2f-b9a57b82e1c2");
                _containeralternatemeasuredvaluelabel3Info = new RepoItemInfo(this, "ContainerAlternateMeasuredValueLabel3", "/container[@controltypename='DtmUserInterface']/container[@controlname='DtmDisplayArea']/?/?/container[@controlname~'TabPage_Menu_Root_DiagnosticPage']/container[@controlname='EddMenuTabPage_MenuPanel']/container[@controlname='EddMenuPanel_ScrollContainer']/container[@controlname='EddMenuPanel_ScrollContainer_ZeroLayoutContainer']//container[@controlname~'NE107_header_DiagnosticGraph']/container[@controlname='EddMenuGroupBox_MenuPanel']//container[@controltypename='DtmPluginHost']/container[@controlname='GuiDashboardProcessVariablesPanelControl']/container[@controlname='MainDashboardPanel']/?/?/container[@controlname='alternateMeasuredValueLabel3']", 30000, null, "a2b3d3cb-f0c6-470c-9139-2e0157b398c8");
                _containeralternatemeasuredvaluelabel4Info = new RepoItemInfo(this, "ContainerAlternateMeasuredValueLabel4", "/container[@controltypename='DtmUserInterface']/container[@controlname='DtmDisplayArea']/?/?/container[@controlname~'TabPage_Menu_Root_DiagnosticPage']/container[@controlname='EddMenuTabPage_MenuPanel']/container[@controlname='EddMenuPanel_ScrollContainer']/container[@controlname='EddMenuPanel_ScrollContainer_ZeroLayoutContainer']//container[@controlname~'NE107_header_DiagnosticGraph']/container[@controlname='EddMenuGroupBox_MenuPanel']//container[@controltypename='DtmPluginHost']/container[@controlname='GuiDashboardProcessVariablesPanelControl']/container[@controlname='MainDashboardPanel']/?/?/container[@controlname='alternateMeasuredValueLabel4']", 30000, null, "5fa4d96d-1e82-424a-ba09-8d28689e6ee9");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("52aede55-fa4d-411a-9152-c974251dfba1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ContainerMainLabel item.
            /// </summary>
            [RepositoryItem("ee2b815b-287b-4997-b9ac-3b348f377cca")]
            public virtual Ranorex.Container ContainerMainLabel
            {
                get
                {
                    return _containermainlabelInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ContainerMainLabel item info.
            /// </summary>
            [RepositoryItemInfo("ee2b815b-287b-4997-b9ac-3b348f377cca")]
            public virtual RepoItemInfo ContainerMainLabelInfo
            {
                get
                {
                    return _containermainlabelInfo;
                }
            }

            /// <summary>
            /// The ContainerAlternateMeasuredValueLabel1 item.
            /// </summary>
            [RepositoryItem("a1ab5820-9896-46ad-bbd0-6189d5b203a9")]
            public virtual Ranorex.Container ContainerAlternateMeasuredValueLabel1
            {
                get
                {
                    return _containeralternatemeasuredvaluelabel1Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ContainerAlternateMeasuredValueLabel1 item info.
            /// </summary>
            [RepositoryItemInfo("a1ab5820-9896-46ad-bbd0-6189d5b203a9")]
            public virtual RepoItemInfo ContainerAlternateMeasuredValueLabel1Info
            {
                get
                {
                    return _containeralternatemeasuredvaluelabel1Info;
                }
            }

            /// <summary>
            /// The ContainerAlternateMeasuredValueLabel2 item.
            /// </summary>
            [RepositoryItem("8561b1a9-053f-4287-9b2f-b9a57b82e1c2")]
            public virtual Ranorex.Container ContainerAlternateMeasuredValueLabel2
            {
                get
                {
                    return _containeralternatemeasuredvaluelabel2Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ContainerAlternateMeasuredValueLabel2 item info.
            /// </summary>
            [RepositoryItemInfo("8561b1a9-053f-4287-9b2f-b9a57b82e1c2")]
            public virtual RepoItemInfo ContainerAlternateMeasuredValueLabel2Info
            {
                get
                {
                    return _containeralternatemeasuredvaluelabel2Info;
                }
            }

            /// <summary>
            /// The ContainerAlternateMeasuredValueLabel3 item.
            /// </summary>
            [RepositoryItem("a2b3d3cb-f0c6-470c-9139-2e0157b398c8")]
            public virtual Ranorex.Container ContainerAlternateMeasuredValueLabel3
            {
                get
                {
                    return _containeralternatemeasuredvaluelabel3Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ContainerAlternateMeasuredValueLabel3 item info.
            /// </summary>
            [RepositoryItemInfo("a2b3d3cb-f0c6-470c-9139-2e0157b398c8")]
            public virtual RepoItemInfo ContainerAlternateMeasuredValueLabel3Info
            {
                get
                {
                    return _containeralternatemeasuredvaluelabel3Info;
                }
            }

            /// <summary>
            /// The ContainerAlternateMeasuredValueLabel4 item.
            /// </summary>
            [RepositoryItem("5fa4d96d-1e82-424a-ba09-8d28689e6ee9")]
            public virtual Ranorex.Container ContainerAlternateMeasuredValueLabel4
            {
                get
                {
                    return _containeralternatemeasuredvaluelabel4Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ContainerAlternateMeasuredValueLabel4 item info.
            /// </summary>
            [RepositoryItemInfo("5fa4d96d-1e82-424a-ba09-8d28689e6ee9")]
            public virtual RepoItemInfo ContainerAlternateMeasuredValueLabel4Info
            {
                get
                {
                    return _containeralternatemeasuredvaluelabel4Info;
                }
            }
        }

        /// <summary>
        /// The ExtendedFolder folder.
        /// </summary>
        [RepositoryFolder("77e17510-d82d-4562-811f-8ccf278b46bd")]
        public partial class ExtendedFolder : RepoGenBaseFolder
        {
            DashboardElementsRepositoryFolders.MainValuesFolder _mainvalues;
            DashboardElementsRepositoryFolders.ExtendedValuesFolder _extendedvalues;

            /// <summary>
            /// Creates a new Extended  folder.
            /// </summary>
            public ExtendedFolder(RepoGenBaseFolder parentFolder) :
                    base("Extended", "", parentFolder, 0, null, false, "77e17510-d82d-4562-811f-8ccf278b46bd", "")
            {
                _mainvalues = new DashboardElementsRepositoryFolders.MainValuesFolder(this);
                _extendedvalues = new DashboardElementsRepositoryFolders.ExtendedValuesFolder(this);
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("77e17510-d82d-4562-811f-8ccf278b46bd")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MainValues folder.
            /// </summary>
            [RepositoryFolder("0798eaf4-db74-4f3e-89cd-254350b3f528")]
            public virtual DashboardElementsRepositoryFolders.MainValuesFolder MainValues
            {
                get { return _mainvalues; }
            }

            /// <summary>
            /// The ExtendedValues folder.
            /// </summary>
            [RepositoryFolder("e04e5038-5855-4a75-acef-9f8e8f863995")]
            public virtual DashboardElementsRepositoryFolders.ExtendedValuesFolder ExtendedValues
            {
                get { return _extendedvalues; }
            }
        }

        /// <summary>
        /// The MainValuesFolder folder.
        /// </summary>
        [RepositoryFolder("0798eaf4-db74-4f3e-89cd-254350b3f528")]
        public partial class MainValuesFolder : RepoGenBaseFolder
        {
            RepoItemInfo _containermainlabelInfo;
            RepoItemInfo _containeralternatemeasuredvaluelabel1Info;
            RepoItemInfo _containeralternatemeasuredvaluelabel2Info;
            RepoItemInfo _containeralternatemeasuredvaluelabel3Info;
            RepoItemInfo _containeralternatemeasuredvaluelabel4Info;

            /// <summary>
            /// Creates a new MainValues  folder.
            /// </summary>
            public MainValuesFolder(RepoGenBaseFolder parentFolder) :
                    base("MainValues", "", parentFolder, 0, null, false, "0798eaf4-db74-4f3e-89cd-254350b3f528", "")
            {
                _containermainlabelInfo = new RepoItemInfo(this, "ContainerMainLabel", "/container[@controltypename='DtmUserInterface']/container[@controlname='DtmDisplayArea']/?/?/container[@controlname~'TabPage_Menu_Root_DiagnosticPage']/container[@controlname='EddMenuTabPage_MenuPanel']/container[@controlname='EddMenuPanel_ScrollContainer']/container[@controlname='EddMenuPanel_ScrollContainer_ZeroLayoutContainer']//container[@controlname~'DiagnosticGraph']/container[@controlname='EddMenuGroupBox_MenuPanel']//container[@controltypename='DtmPluginHost']/container[@controlname='GuiDashboardProcessVariablesPanelControl']/element[@controlname='TabControl']/container/container/container/container[@controlname='label']", 30000, null, "7e3c7fb2-49a7-42fa-a3aa-38df92ec6d4a");
                _containeralternatemeasuredvaluelabel1Info = new RepoItemInfo(this, "ContainerAlternateMeasuredValueLabel1", "/container[@controltypename='DtmUserInterface']/container[@controlname='DtmDisplayArea']/?/?/container[@controlname~'TabPage_Menu_Root_DiagnosticPage']/container[@controlname='EddMenuTabPage_MenuPanel']/container[@controlname='EddMenuPanel_ScrollContainer']/container[@controlname='EddMenuPanel_ScrollContainer_ZeroLayoutContainer']//container[@controlname~'DiagnosticGraph']/container[@controlname='EddMenuGroupBox_MenuPanel']//container[@controltypename='DtmPluginHost']/container[@controlname='GuiDashboardProcessVariablesPanelControl']/element[@controlname='TabControl']/container/container/container/container[@controlname='alternateMeasuredValueLabel1']", 30000, null, "4f6d5de2-66cc-4154-ab0c-01b42c2d6bad");
                _containeralternatemeasuredvaluelabel2Info = new RepoItemInfo(this, "ContainerAlternateMeasuredValueLabel2", "/container[@controltypename='DtmUserInterface']/container[@controlname='DtmDisplayArea']/?/?/container[@controlname~'TabPage_Menu_Root_DiagnosticPage']/container[@controlname='EddMenuTabPage_MenuPanel']/container[@controlname='EddMenuPanel_ScrollContainer']/container[@controlname='EddMenuPanel_ScrollContainer_ZeroLayoutContainer']//container[@controlname~'DiagnosticGraph']/container[@controlname='EddMenuGroupBox_MenuPanel']//container[@controltypename='DtmPluginHost']/container[@controlname='GuiDashboardProcessVariablesPanelControl']/element[@controlname='TabControl']/container/container/container/container[@controlname='alternateMeasuredValueLabel2']", 30000, null, "0b8c52e0-9cc5-4798-a6a9-58ce23b3fbbd");
                _containeralternatemeasuredvaluelabel3Info = new RepoItemInfo(this, "ContainerAlternateMeasuredValueLabel3", "/container[@controltypename='DtmUserInterface']/container[@controlname='DtmDisplayArea']/?/?/container[@controlname~'TabPage_Menu_Root_DiagnosticPage']/container[@controlname='EddMenuTabPage_MenuPanel']/container[@controlname='EddMenuPanel_ScrollContainer']/container[@controlname='EddMenuPanel_ScrollContainer_ZeroLayoutContainer']//container[@controlname~'DiagnosticGraph']/container[@controlname='EddMenuGroupBox_MenuPanel']//container[@controltypename='DtmPluginHost']/container[@controlname='GuiDashboardProcessVariablesPanelControl']/element[@controlname='TabControl']/container/container/container/container[@controlname='alternateMeasuredValueLabel3']", 30000, null, "2531f9d3-2d25-4cce-8786-fe33f21acf3b");
                _containeralternatemeasuredvaluelabel4Info = new RepoItemInfo(this, "ContainerAlternateMeasuredValueLabel4", "/container[@controltypename='DtmUserInterface']/container[@controlname='DtmDisplayArea']/?/?/container[@controlname~'TabPage_Menu_Root_DiagnosticPage']/container[@controlname='EddMenuTabPage_MenuPanel']/container[@controlname='EddMenuPanel_ScrollContainer']/container[@controlname='EddMenuPanel_ScrollContainer_ZeroLayoutContainer']//container[@controlname~'DiagnosticGraph']/container[@controlname='EddMenuGroupBox_MenuPanel']//container[@controltypename='DtmPluginHost']/container[@controlname='GuiDashboardProcessVariablesPanelControl']/element[@controlname='TabControl']/container/container/container/container[@controlname='alternateMeasuredValueLabel4']", 30000, null, "deea35cd-9258-4e8a-8a04-51dc8dcf985e");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0798eaf4-db74-4f3e-89cd-254350b3f528")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ContainerMainLabel item.
            /// </summary>
            [RepositoryItem("7e3c7fb2-49a7-42fa-a3aa-38df92ec6d4a")]
            public virtual Ranorex.Container ContainerMainLabel
            {
                get
                {
                    return _containermainlabelInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ContainerMainLabel item info.
            /// </summary>
            [RepositoryItemInfo("7e3c7fb2-49a7-42fa-a3aa-38df92ec6d4a")]
            public virtual RepoItemInfo ContainerMainLabelInfo
            {
                get
                {
                    return _containermainlabelInfo;
                }
            }

            /// <summary>
            /// The ContainerAlternateMeasuredValueLabel1 item.
            /// </summary>
            [RepositoryItem("4f6d5de2-66cc-4154-ab0c-01b42c2d6bad")]
            public virtual Ranorex.Container ContainerAlternateMeasuredValueLabel1
            {
                get
                {
                    return _containeralternatemeasuredvaluelabel1Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ContainerAlternateMeasuredValueLabel1 item info.
            /// </summary>
            [RepositoryItemInfo("4f6d5de2-66cc-4154-ab0c-01b42c2d6bad")]
            public virtual RepoItemInfo ContainerAlternateMeasuredValueLabel1Info
            {
                get
                {
                    return _containeralternatemeasuredvaluelabel1Info;
                }
            }

            /// <summary>
            /// The ContainerAlternateMeasuredValueLabel2 item.
            /// </summary>
            [RepositoryItem("0b8c52e0-9cc5-4798-a6a9-58ce23b3fbbd")]
            public virtual Ranorex.Container ContainerAlternateMeasuredValueLabel2
            {
                get
                {
                    return _containeralternatemeasuredvaluelabel2Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ContainerAlternateMeasuredValueLabel2 item info.
            /// </summary>
            [RepositoryItemInfo("0b8c52e0-9cc5-4798-a6a9-58ce23b3fbbd")]
            public virtual RepoItemInfo ContainerAlternateMeasuredValueLabel2Info
            {
                get
                {
                    return _containeralternatemeasuredvaluelabel2Info;
                }
            }

            /// <summary>
            /// The ContainerAlternateMeasuredValueLabel3 item.
            /// </summary>
            [RepositoryItem("2531f9d3-2d25-4cce-8786-fe33f21acf3b")]
            public virtual Ranorex.Container ContainerAlternateMeasuredValueLabel3
            {
                get
                {
                    return _containeralternatemeasuredvaluelabel3Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ContainerAlternateMeasuredValueLabel3 item info.
            /// </summary>
            [RepositoryItemInfo("2531f9d3-2d25-4cce-8786-fe33f21acf3b")]
            public virtual RepoItemInfo ContainerAlternateMeasuredValueLabel3Info
            {
                get
                {
                    return _containeralternatemeasuredvaluelabel3Info;
                }
            }

            /// <summary>
            /// The ContainerAlternateMeasuredValueLabel4 item.
            /// </summary>
            [RepositoryItem("deea35cd-9258-4e8a-8a04-51dc8dcf985e")]
            public virtual Ranorex.Container ContainerAlternateMeasuredValueLabel4
            {
                get
                {
                    return _containeralternatemeasuredvaluelabel4Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ContainerAlternateMeasuredValueLabel4 item info.
            /// </summary>
            [RepositoryItemInfo("deea35cd-9258-4e8a-8a04-51dc8dcf985e")]
            public virtual RepoItemInfo ContainerAlternateMeasuredValueLabel4Info
            {
                get
                {
                    return _containeralternatemeasuredvaluelabel4Info;
                }
            }
        }

        /// <summary>
        /// The ExtendedValuesFolder folder.
        /// </summary>
        [RepositoryFolder("e04e5038-5855-4a75-acef-9f8e8f863995")]
        public partial class ExtendedValuesFolder : RepoGenBaseFolder
        {
            RepoItemInfo _containerextendedmeasuredvaluelabel1Info;
            RepoItemInfo _containerextendedmeasuredvaluelabel2Info;
            RepoItemInfo _containerextendedmeasuredvaluelabel3Info;
            RepoItemInfo _containerextendedmeasuredvaluelabel4Info;
            RepoItemInfo _containerextendedmeasuredvaluelabel5Info;
            RepoItemInfo _containerextendedmeasuredvaluelabel6Info;
            RepoItemInfo _containerextendedmeasuredvaluelabel7Info;
            RepoItemInfo _containerextendedmeasuredvaluelabel8Info;

            /// <summary>
            /// Creates a new ExtendedValues  folder.
            /// </summary>
            public ExtendedValuesFolder(RepoGenBaseFolder parentFolder) :
                    base("ExtendedValues", "", parentFolder, 0, null, false, "e04e5038-5855-4a75-acef-9f8e8f863995", "")
            {
                _containerextendedmeasuredvaluelabel1Info = new RepoItemInfo(this, "ContainerExtendedMeasuredValueLabel1", "/container[@controltypename='DtmUserInterface']/container[@controlname='DtmDisplayArea']/?/?/container[@controlname~'TabPage_Menu_Root_DiagnosticPage']/container[@controlname='EddMenuTabPage_MenuPanel']/container[@controlname='EddMenuPanel_ScrollContainer']/container[@controlname='EddMenuPanel_ScrollContainer_ZeroLayoutContainer']//container[@controlname~'DiagnosticGraph']/container[@controlname='EddMenuGroupBox_MenuPanel']//container[@controltypename='DtmPluginHost']/container[@controlname='GuiDashboardProcessVariablesPanelControl']/element[@controlname='TabControl']/container/container/container[@controlname='extendedMeasuredValueLabel1']", 30000, null, "b3bcf232-a656-476e-be81-7d0e87f4cb3d");
                _containerextendedmeasuredvaluelabel2Info = new RepoItemInfo(this, "ContainerExtendedMeasuredValueLabel2", "/container[@controltypename='DtmUserInterface']/container[@controlname='DtmDisplayArea']/?/?/container[@controlname~'TabPage_Menu_Root_DiagnosticPage']/container[@controlname='EddMenuTabPage_MenuPanel']/container[@controlname='EddMenuPanel_ScrollContainer']/container[@controlname='EddMenuPanel_ScrollContainer_ZeroLayoutContainer']//container[@controlname~'DiagnosticGraph']/container[@controlname='EddMenuGroupBox_MenuPanel']//container[@controltypename='DtmPluginHost']/container[@controlname='GuiDashboardProcessVariablesPanelControl']/element[@controlname='TabControl']/container/container/container[@controlname='extendedMeasuredValueLabel2']", 30000, null, "3038cb0e-09d7-4701-bf90-9c42503b5f47");
                _containerextendedmeasuredvaluelabel3Info = new RepoItemInfo(this, "ContainerExtendedMeasuredValueLabel3", "/container[@controltypename='DtmUserInterface']/container[@controlname='DtmDisplayArea']/?/?/container[@controlname~'TabPage_Menu_Root_DiagnosticPage']/container[@controlname='EddMenuTabPage_MenuPanel']/container[@controlname='EddMenuPanel_ScrollContainer']/container[@controlname='EddMenuPanel_ScrollContainer_ZeroLayoutContainer']//container[@controlname~'DiagnosticGraph']/container[@controlname='EddMenuGroupBox_MenuPanel']//container[@controltypename='DtmPluginHost']/container[@controlname='GuiDashboardProcessVariablesPanelControl']/element[@controlname='TabControl']/container/container/container[@controlname='extendedMeasuredValueLabel3']", 30000, null, "630945d5-6f5e-4601-859c-d443379782ff");
                _containerextendedmeasuredvaluelabel4Info = new RepoItemInfo(this, "ContainerExtendedMeasuredValueLabel4", "/container[@controltypename='DtmUserInterface']/container[@controlname='DtmDisplayArea']/?/?/container[@controlname~'TabPage_Menu_Root_DiagnosticPage']/container[@controlname='EddMenuTabPage_MenuPanel']/container[@controlname='EddMenuPanel_ScrollContainer']/container[@controlname='EddMenuPanel_ScrollContainer_ZeroLayoutContainer']//container[@controlname~'DiagnosticGraph']/container[@controlname='EddMenuGroupBox_MenuPanel']//container[@controltypename='DtmPluginHost']/container[@controlname='GuiDashboardProcessVariablesPanelControl']/element[@controlname='TabControl']/container/container/container[@controlname='extendedMeasuredValueLabel4']", 30000, null, "b1baba5a-d882-4db5-9db3-1aaf26165a66");
                _containerextendedmeasuredvaluelabel5Info = new RepoItemInfo(this, "ContainerExtendedMeasuredValueLabel5", "/container[@controltypename='DtmUserInterface']/container[@controlname='DtmDisplayArea']/?/?/container[@controlname~'TabPage_Menu_Root_DiagnosticPage']/container[@controlname='EddMenuTabPage_MenuPanel']/container[@controlname='EddMenuPanel_ScrollContainer']/container[@controlname='EddMenuPanel_ScrollContainer_ZeroLayoutContainer']//container[@controlname~'DiagnosticGraph']/container[@controlname='EddMenuGroupBox_MenuPanel']//container[@controltypename='DtmPluginHost']/container[@controlname='GuiDashboardProcessVariablesPanelControl']/element[@controlname='TabControl']/container/container/container[@controlname='extendedMeasuredValueLabel5']", 30000, null, "accb90d9-d946-47da-a2ad-7b5eaffb4291");
                _containerextendedmeasuredvaluelabel6Info = new RepoItemInfo(this, "ContainerExtendedMeasuredValueLabel6", "/container[@controltypename='DtmUserInterface']/container[@controlname='DtmDisplayArea']/?/?/container[@controlname~'TabPage_Menu_Root_DiagnosticPage']/container[@controlname='EddMenuTabPage_MenuPanel']/container[@controlname='EddMenuPanel_ScrollContainer']/container[@controlname='EddMenuPanel_ScrollContainer_ZeroLayoutContainer']//container[@controlname~'DiagnosticGraph']/container[@controlname='EddMenuGroupBox_MenuPanel']//container[@controltypename='DtmPluginHost']/container[@controlname='GuiDashboardProcessVariablesPanelControl']/element[@controlname='TabControl']/container/container/container[@controlname='extendedMeasuredValueLabel6']", 30000, null, "f0963e2b-973e-45b6-911c-afa1d8f9b073");
                _containerextendedmeasuredvaluelabel7Info = new RepoItemInfo(this, "ContainerExtendedMeasuredValueLabel7", "/container[@controltypename='DtmUserInterface']/container[@controlname='DtmDisplayArea']/?/?/container[@controlname~'TabPage_Menu_Root_DiagnosticPage']/container[@controlname='EddMenuTabPage_MenuPanel']/container[@controlname='EddMenuPanel_ScrollContainer']/container[@controlname='EddMenuPanel_ScrollContainer_ZeroLayoutContainer']//container[@controlname~'DiagnosticGraph']/container[@controlname='EddMenuGroupBox_MenuPanel']//container[@controltypename='DtmPluginHost']/container[@controlname='GuiDashboardProcessVariablesPanelControl']/element[@controlname='TabControl']/container/container/container[@controlname='extendedMeasuredValueLabel7']", 30000, null, "c63441c9-f445-43fc-82cb-d75f0ddd286c");
                _containerextendedmeasuredvaluelabel8Info = new RepoItemInfo(this, "ContainerExtendedMeasuredValueLabel8", "/container[@controltypename='DtmUserInterface']/container[@controlname='DtmDisplayArea']/?/?/container[@controlname~'TabPage_Menu_Root_DiagnosticPage']/container[@controlname='EddMenuTabPage_MenuPanel']/container[@controlname='EddMenuPanel_ScrollContainer']/container[@controlname='EddMenuPanel_ScrollContainer_ZeroLayoutContainer']//container[@controlname~'DiagnosticGraph']/container[@controlname='EddMenuGroupBox_MenuPanel']//container[@controltypename='DtmPluginHost']/container[@controlname='GuiDashboardProcessVariablesPanelControl']/element[@controlname='TabControl']/container/container/container[@controlname='extendedMeasuredValueLabel8']", 30000, null, "1fb85878-bdfe-4c3e-ac8c-b6786416d1e1");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e04e5038-5855-4a75-acef-9f8e8f863995")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ContainerExtendedMeasuredValueLabel1 item.
            /// </summary>
            [RepositoryItem("b3bcf232-a656-476e-be81-7d0e87f4cb3d")]
            public virtual Ranorex.Container ContainerExtendedMeasuredValueLabel1
            {
                get
                {
                    return _containerextendedmeasuredvaluelabel1Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ContainerExtendedMeasuredValueLabel1 item info.
            /// </summary>
            [RepositoryItemInfo("b3bcf232-a656-476e-be81-7d0e87f4cb3d")]
            public virtual RepoItemInfo ContainerExtendedMeasuredValueLabel1Info
            {
                get
                {
                    return _containerextendedmeasuredvaluelabel1Info;
                }
            }

            /// <summary>
            /// The ContainerExtendedMeasuredValueLabel2 item.
            /// </summary>
            [RepositoryItem("3038cb0e-09d7-4701-bf90-9c42503b5f47")]
            public virtual Ranorex.Container ContainerExtendedMeasuredValueLabel2
            {
                get
                {
                    return _containerextendedmeasuredvaluelabel2Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ContainerExtendedMeasuredValueLabel2 item info.
            /// </summary>
            [RepositoryItemInfo("3038cb0e-09d7-4701-bf90-9c42503b5f47")]
            public virtual RepoItemInfo ContainerExtendedMeasuredValueLabel2Info
            {
                get
                {
                    return _containerextendedmeasuredvaluelabel2Info;
                }
            }

            /// <summary>
            /// The ContainerExtendedMeasuredValueLabel3 item.
            /// </summary>
            [RepositoryItem("630945d5-6f5e-4601-859c-d443379782ff")]
            public virtual Ranorex.Container ContainerExtendedMeasuredValueLabel3
            {
                get
                {
                    return _containerextendedmeasuredvaluelabel3Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ContainerExtendedMeasuredValueLabel3 item info.
            /// </summary>
            [RepositoryItemInfo("630945d5-6f5e-4601-859c-d443379782ff")]
            public virtual RepoItemInfo ContainerExtendedMeasuredValueLabel3Info
            {
                get
                {
                    return _containerextendedmeasuredvaluelabel3Info;
                }
            }

            /// <summary>
            /// The ContainerExtendedMeasuredValueLabel4 item.
            /// </summary>
            [RepositoryItem("b1baba5a-d882-4db5-9db3-1aaf26165a66")]
            public virtual Ranorex.Container ContainerExtendedMeasuredValueLabel4
            {
                get
                {
                    return _containerextendedmeasuredvaluelabel4Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ContainerExtendedMeasuredValueLabel4 item info.
            /// </summary>
            [RepositoryItemInfo("b1baba5a-d882-4db5-9db3-1aaf26165a66")]
            public virtual RepoItemInfo ContainerExtendedMeasuredValueLabel4Info
            {
                get
                {
                    return _containerextendedmeasuredvaluelabel4Info;
                }
            }

            /// <summary>
            /// The ContainerExtendedMeasuredValueLabel5 item.
            /// </summary>
            [RepositoryItem("accb90d9-d946-47da-a2ad-7b5eaffb4291")]
            public virtual Ranorex.Container ContainerExtendedMeasuredValueLabel5
            {
                get
                {
                    return _containerextendedmeasuredvaluelabel5Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ContainerExtendedMeasuredValueLabel5 item info.
            /// </summary>
            [RepositoryItemInfo("accb90d9-d946-47da-a2ad-7b5eaffb4291")]
            public virtual RepoItemInfo ContainerExtendedMeasuredValueLabel5Info
            {
                get
                {
                    return _containerextendedmeasuredvaluelabel5Info;
                }
            }

            /// <summary>
            /// The ContainerExtendedMeasuredValueLabel6 item.
            /// </summary>
            [RepositoryItem("f0963e2b-973e-45b6-911c-afa1d8f9b073")]
            public virtual Ranorex.Container ContainerExtendedMeasuredValueLabel6
            {
                get
                {
                    return _containerextendedmeasuredvaluelabel6Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ContainerExtendedMeasuredValueLabel6 item info.
            /// </summary>
            [RepositoryItemInfo("f0963e2b-973e-45b6-911c-afa1d8f9b073")]
            public virtual RepoItemInfo ContainerExtendedMeasuredValueLabel6Info
            {
                get
                {
                    return _containerextendedmeasuredvaluelabel6Info;
                }
            }

            /// <summary>
            /// The ContainerExtendedMeasuredValueLabel7 item.
            /// </summary>
            [RepositoryItem("c63441c9-f445-43fc-82cb-d75f0ddd286c")]
            public virtual Ranorex.Container ContainerExtendedMeasuredValueLabel7
            {
                get
                {
                    return _containerextendedmeasuredvaluelabel7Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ContainerExtendedMeasuredValueLabel7 item info.
            /// </summary>
            [RepositoryItemInfo("c63441c9-f445-43fc-82cb-d75f0ddd286c")]
            public virtual RepoItemInfo ContainerExtendedMeasuredValueLabel7Info
            {
                get
                {
                    return _containerextendedmeasuredvaluelabel7Info;
                }
            }

            /// <summary>
            /// The ContainerExtendedMeasuredValueLabel8 item.
            /// </summary>
            [RepositoryItem("1fb85878-bdfe-4c3e-ac8c-b6786416d1e1")]
            public virtual Ranorex.Container ContainerExtendedMeasuredValueLabel8
            {
                get
                {
                    return _containerextendedmeasuredvaluelabel8Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ContainerExtendedMeasuredValueLabel8 item info.
            /// </summary>
            [RepositoryItemInfo("1fb85878-bdfe-4c3e-ac8c-b6786416d1e1")]
            public virtual RepoItemInfo ContainerExtendedMeasuredValueLabel8Info
            {
                get
                {
                    return _containerextendedmeasuredvaluelabel8Info;
                }
            }
        }

    }
#pragma warning restore 0436
}