///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

namespace EH.PCPS.TestAutomation.DeviceCare.V10300.Functions.ApplicationArea.Page_DeviceScreen.Execution
{
    using Ranorex;
    using Ranorex.Core.Testing;

#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The LoadOrignalDTMData recording.
    /// </summary>
    [TestModule("5f328b14-ae89-47d3-b16c-0d43594e0ae9", ModuleType.Recording, 1)]
    public partial class LoadOrignalDTMData : ITestModule
    {
        /// <summary>
        /// Holds an instance of the EH.PCPS.TestAutomation.DeviceCare.V10300.GUI.DeviceCareApplication repository.
        /// </summary>
        public static EH.PCPS.TestAutomation.DeviceCare.V10300.GUI.DeviceCareApplication repo = EH.PCPS.TestAutomation.DeviceCare.V10300.GUI.DeviceCareApplication.Instance;

        static LoadOrignalDTMData instance = new LoadOrignalDTMData();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public LoadOrignalDTMData()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static LoadOrignalDTMData Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MenuArea.MainMenu.ProgramFunctions' at Center.", repo.MenuArea.MainMenu.ProgramFunctionsInfo, new RecordItemIndex(0));
            repo.MenuArea.MainMenu.ProgramFunctions.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DeviceCare.MenuArea.Menu_DeviceScreen.DTMFunctionMenutop.acess.SubMenu.RestoreButton' at 84;45.", repo.DeviceCare.MenuArea.Menu_DeviceScreen.DTMFunctionMenutop.acess.SubMenu.RestoreButtonInfo, new RecordItemIndex(1));
            repo.DeviceCare.MenuArea.Menu_DeviceScreen.DTMFunctionMenutop.acess.SubMenu.RestoreButton.Click("84;45");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DeviceCare.MenuArea.Menu_DeviceScreen.DTMFunctionMenutop.AutomIdCUsersPublicDocumentsEndres' at 98;37.", repo.DeviceCare.MenuArea.Menu_DeviceScreen.DTMFunctionMenutop.AutomIdCUsersPublicDocumentsEndresInfo, new RecordItemIndex(2));
            repo.DeviceCare.MenuArea.Menu_DeviceScreen.DTMFunctionMenutop.AutomIdCUsersPublicDocumentsEndres.Click("98;37");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dialog.DeviceCare_MessageBox.ButtonYes' at Center.", repo.Dialog.ConfirmRestoreDeviceData.ButtonYesInfo, new RecordItemIndex(3));
            repo.Dialog.ConfirmRestoreDeviceData.ButtonYes.Click();
            Delay.Milliseconds(200);    
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
