///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace EH.PCPS.TestAutomation.TestPackageUpdateA2016.SaveRestore.GUI.MenuArea.Toolbar
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Toolbar element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    [RepositoryFolder("12146e85-b7b8-4d41-bc0a-46e0516a9bbe")]
    public partial class Toolbar : RepoGenBaseFolder
    {
        static Toolbar instance = new Toolbar();
        ToolbarFolders.ToolbarRepositoryAppFolder _toolbarrepository;

        /// <summary>
        /// Gets the singleton class instance representing the Toolbar element repository.
        /// </summary>
        [RepositoryFolder("12146e85-b7b8-4d41-bc0a-46e0516a9bbe")]
        public static Toolbar Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Toolbar() 
            : base("Toolbar", "/", null, 0, false, "12146e85-b7b8-4d41-bc0a-46e0516a9bbe", ".\\RepositoryImages\\Toolbar12146e85.rximgres")
        {
            _toolbarrepository = new ToolbarFolders.ToolbarRepositoryAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("12146e85-b7b8-4d41-bc0a-46e0516a9bbe")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The toolbarRepository folder.
        /// </summary>
        [RepositoryFolder("84dbe6d3-ee34-4fa4-8429-7581e46b9946")]
        public virtual ToolbarFolders.ToolbarRepositoryAppFolder toolbarRepository
        {
            get { return _toolbarrepository; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    public partial class ToolbarFolders
    {
        /// <summary>
        /// The ToolbarRepositoryAppFolder folder.
        /// </summary>
        [RepositoryFolder("84dbe6d3-ee34-4fa4-8429-7581e46b9946")]
        public partial class ToolbarRepositoryAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonparameterselectionInfo;

            /// <summary>
            /// Creates a new toolbarRepository  folder.
            /// </summary>
            public ToolbarRepositoryAppFolder(RepoGenBaseFolder parentFolder) :
                    base("toolbarRepository", "/container[@controltypename='DtmUserInterface']/container[@controlname='DtmToolBar']/element/element/toolbar", parentFolder, 30000, null, true, "84dbe6d3-ee34-4fa4-8429-7581e46b9946", "")
            {
                _buttonparameterselectionInfo = new RepoItemInfo(this, "buttonParameterSelection", "button[@childindex=0]", 30000, null, "c313843f-dbe1-4162-973d-3e30a4637350");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("84dbe6d3-ee34-4fa4-8429-7581e46b9946")]
            public virtual Ranorex.ToolBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ToolBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("84dbe6d3-ee34-4fa4-8429-7581e46b9946")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The buttonParameterSelection item.
            /// </summary>
            [RepositoryItem("c313843f-dbe1-4162-973d-3e30a4637350")]
            public virtual Ranorex.Button buttonParameterSelection
            {
                get
                {
                    return _buttonparameterselectionInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The buttonParameterSelection item info.
            /// </summary>
            [RepositoryItemInfo("c313843f-dbe1-4162-973d-3e30a4637350")]
            public virtual RepoItemInfo buttonParameterSelectionInfo
            {
                get
                {
                    return _buttonparameterselectionInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}