///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace EH.PCPS.TestAutomation.TestPackageUpdateA2017.Historom.GUI.StatusArea.Usermessages
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the UsermessageElements element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    [RepositoryFolder("9b2ee072-8893-439f-bb2f-89fadf082e9b")]
    public partial class UsermessageElements : RepoGenBaseFolder
    {
        static UsermessageElements instance = new UsermessageElements();
        RepoItemInfo _infotextInfo;

        /// <summary>
        /// Gets the singleton class instance representing the UsermessageElements element repository.
        /// </summary>
        [RepositoryFolder("9b2ee072-8893-439f-bb2f-89fadf082e9b")]
        public static UsermessageElements Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public UsermessageElements() 
            : base("UsermessageElements", "/", null, 0, false, "9b2ee072-8893-439f-bb2f-89fadf082e9b", ".\\RepositoryImages\\UsermessageElements9b2ee072.rximgres")
        {
            _infotextInfo = new RepoItemInfo(this, "InfoText", "/container[@automationid='HistoROMModule.HistoROMForm.Form']/element[@automationid='HistoROMModule.MessageControl.Messages']/text/text[@accessiblename='HistoROMModule.MessageControl.Messages']", 30000, null, "6755386c-6f93-4766-b72e-50624a866b93");
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("9b2ee072-8893-439f-bb2f-89fadf082e9b")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The InfoText item.
        /// </summary>
        [RepositoryItem("6755386c-6f93-4766-b72e-50624a866b93")]
        public virtual Ranorex.Text InfoText
        {
            get
            {
                 return _infotextInfo.CreateAdapter<Ranorex.Text>(true);
            }
        }

        /// <summary>
        /// The InfoText item info.
        /// </summary>
        [RepositoryItemInfo("6755386c-6f93-4766-b72e-50624a866b93")]
        public virtual RepoItemInfo InfoTextInfo
        {
            get
            {
                return _infotextInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    public partial class UsermessageElementsFolders
    {
    }
#pragma warning restore 0436
}