///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace EH.PCPS.TestAutomation.DeviceCare.V10300.Functions.MenuArea.Menu_Settings.Validation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CheckMenuSettings recording.
    /// </summary>
    [TestModule("89d0d8d3-5e2c-4f6b-a6bc-ac08bf049c2a", ModuleType.Recording, 1)]
    public partial class CheckMenuSettings : ITestModule
    {
        /// <summary>
        /// Holds an instance of the EH.PCPS.TestAutomation.DeviceCare.V10300.GUI.DeviceCareApplication repository.
        /// </summary>
        public static EH.PCPS.TestAutomation.DeviceCare.V10300.GUI.DeviceCareApplication repo = EH.PCPS.TestAutomation.DeviceCare.V10300.GUI.DeviceCareApplication.Instance;

        static CheckMenuSettings instance = new CheckMenuSettings();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CheckMenuSettings()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CheckMenuSettings Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (Visible='true') on item 'MenuArea.MainMenu.SettingsMenuItems.ButtonEventLog'.", repo.MenuArea.MainMenu.SettingsMenuItems.ButtonEventLogInfo, new RecordItemIndex(0));
                Validate.Attribute(repo.MenuArea.MainMenu.SettingsMenuItems.ButtonEventLogInfo, "Visible", "true", Validate.DefaultMessage, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(0)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (Visible='true') on item 'MenuArea.MainMenu.SettingsMenuItems.Text_ButtonEventLog'.", repo.MenuArea.MainMenu.SettingsMenuItems.Text_ButtonEventLogInfo, new RecordItemIndex(1));
                Validate.Attribute(repo.MenuArea.MainMenu.SettingsMenuItems.Text_ButtonEventLogInfo, "Visible", "true", Validate.DefaultMessage, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(1)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (Visible='true') on item 'MenuArea.MainMenu.SettingsMenuItems.ButtonDtmCatalog'.", repo.MenuArea.MainMenu.SettingsMenuItems.ButtonDtmCatalogInfo, new RecordItemIndex(2));
                Validate.Attribute(repo.MenuArea.MainMenu.SettingsMenuItems.ButtonDtmCatalogInfo, "Visible", "true", Validate.DefaultMessage, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(2)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (Visible='true') on item 'MenuArea.MainMenu.SettingsMenuItems.Text_ButtonDtmCatalog'.", repo.MenuArea.MainMenu.SettingsMenuItems.Text_ButtonDtmCatalogInfo, new RecordItemIndex(3));
                Validate.Attribute(repo.MenuArea.MainMenu.SettingsMenuItems.Text_ButtonDtmCatalogInfo, "Visible", "true", Validate.DefaultMessage, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(3)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (Visible='true') on item 'MenuArea.MainMenu.SettingsMenuItems.ButtonLanguage'.", repo.MenuArea.MainMenu.SettingsMenuItems.ButtonLanguageInfo, new RecordItemIndex(4));
                Validate.Attribute(repo.MenuArea.MainMenu.SettingsMenuItems.ButtonLanguageInfo, "Visible", "true", Validate.DefaultMessage, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(4)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (Visible='true') on item 'MenuArea.MainMenu.SettingsMenuItems.Text_ButtonFirmware'.", repo.MenuArea.MainMenu.SettingsMenuItems.Text_ButtonFirmwareInfo, new RecordItemIndex(5));
                Validate.Attribute(repo.MenuArea.MainMenu.SettingsMenuItems.Text_ButtonFirmwareInfo, "Visible", "true", Validate.DefaultMessage, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(5)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (Visible='true') on item 'MenuArea.MainMenu.SettingsMenuItems.ButtonFirmware'.", repo.MenuArea.MainMenu.SettingsMenuItems.ButtonFirmwareInfo, new RecordItemIndex(6));
                Validate.Attribute(repo.MenuArea.MainMenu.SettingsMenuItems.ButtonFirmwareInfo, "Visible", "true", Validate.DefaultMessage, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(6)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (Visible='true') on item 'MenuArea.MainMenu.SettingsMenuItems.Text_ButtonLanguage'.", repo.MenuArea.MainMenu.SettingsMenuItems.Text_ButtonLanguageInfo, new RecordItemIndex(7));
                Validate.Attribute(repo.MenuArea.MainMenu.SettingsMenuItems.Text_ButtonLanguageInfo, "Visible", "true", Validate.DefaultMessage, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(7)); }
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
