///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace EH.PCPS.TestAutomation.TestPackageUpdateA2016.Viscosity.GUI.StatusArea.Statusbar
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the StatusbarElementsRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    [RepositoryFolder("cfe7e7f3-ed10-4a10-9f46-51b13d361cc5")]
    public partial class StatusbarElementsRepository : RepoGenBaseFolder
    {
        static StatusbarElementsRepository instance = new StatusbarElementsRepository();
        RepoItemInfo _txtconnectionstateInfo;
        RepoItemInfo _buttonoperationinprogressInfo;

        /// <summary>
        /// Gets the singleton class instance representing the StatusbarElementsRepository element repository.
        /// </summary>
        [RepositoryFolder("cfe7e7f3-ed10-4a10-9f46-51b13d361cc5")]
        public static StatusbarElementsRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public StatusbarElementsRepository() 
            : base("StatusbarElementsRepository", "/", null, 0, false, "cfe7e7f3-ed10-4a10-9f46-51b13d361cc5", ".\\RepositoryImages\\StatusbarElementsRepositorycfe7e7f3.rximgres")
        {
            _txtconnectionstateInfo = new RepoItemInfo(this, "TxtConnectionState", "/container[@automationid='ViscosityModule.ViscosityForm.Form']/element[@automationid='ViscosityModule.StatusBarControl.StatusBar']/element[@controlname='barDockControlTop']/?/?/toolbar[@accessiblename='Bar']/text[@childindex='0']", 30000, null, "388b3d68-c08d-4bed-a218-6502613d153c");
            _buttonoperationinprogressInfo = new RepoItemInfo(this, "ButtonOperationInProgress", "/container[@automationid='ViscosityModule.ViscosityForm.Form']/element[@automationid='ViscosityModule.StatusBarControl.StatusBar']/element[@controlname='barDockControlTop']/?/?/toolbar[@accessiblename='Bar']/button[@accessiblename~'^Statusbar\\.Item\\.OperationP']", 30000, null, "c728a83b-edbd-4d7a-abd9-7604e3b8013c");
        }

#region Variables

        string _index = "0";

        /// <summary>
        /// Gets or sets the value of variable index.
        /// </summary>
        [TestVariable("64e301a0-902c-4c9b-8abf-a579a46e2c54")]
        public string index
        {
            get { return _index; }
            set { _index = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("cfe7e7f3-ed10-4a10-9f46-51b13d361cc5")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The TxtConnectionState item.
        /// </summary>
        [RepositoryItem("388b3d68-c08d-4bed-a218-6502613d153c")]
        public virtual Ranorex.Text TxtConnectionState
        {
            get
            {
                 return _txtconnectionstateInfo.CreateAdapter<Ranorex.Text>(true);
            }
        }

        /// <summary>
        /// The TxtConnectionState item info.
        /// </summary>
        [RepositoryItemInfo("388b3d68-c08d-4bed-a218-6502613d153c")]
        public virtual RepoItemInfo TxtConnectionStateInfo
        {
            get
            {
                return _txtconnectionstateInfo;
            }
        }

        /// <summary>
        /// The ButtonOperationInProgress item.
        /// </summary>
        [RepositoryItem("c728a83b-edbd-4d7a-abd9-7604e3b8013c")]
        public virtual Ranorex.Button ButtonOperationInProgress
        {
            get
            {
                 return _buttonoperationinprogressInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The ButtonOperationInProgress item info.
        /// </summary>
        [RepositoryItemInfo("c728a83b-edbd-4d7a-abd9-7604e3b8013c")]
        public virtual RepoItemInfo ButtonOperationInProgressInfo
        {
            get
            {
                return _buttonoperationinprogressInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    public partial class StatusbarElementsRepositoryFolders
    {
    }
#pragma warning restore 0436
}