///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace EH.PCPS.TestAutomation.TestPackageUpdateB2014.Compare.GUI.ApplicationArea.MainView
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the ActionButtons element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    [RepositoryFolder("22ad0338-aa3f-4f98-a85e-7bcb80f52722")]
    public partial class ActionButtons : RepoGenBaseFolder
    {
        static ActionButtons instance = new ActionButtons();
        RepoItemInfo _buttoncompareInfo;
        RepoItemInfo _buttoncancelInfo;

        /// <summary>
        /// Gets the singleton class instance representing the ActionButtons element repository.
        /// </summary>
        [RepositoryFolder("22ad0338-aa3f-4f98-a85e-7bcb80f52722")]
        public static ActionButtons Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public ActionButtons() 
            : base("ActionButtons", "/", null, 0, false, "22ad0338-aa3f-4f98-a85e-7bcb80f52722", ".\\RepositoryImages\\ActionButtons22ad0338.rximgres")
        {
            _buttoncompareInfo = new RepoItemInfo(this, "buttonCompare", "/container[@controltypename='DtmUserInterface']/container[@controlname='DatasetComparisonPresentation']/container[@controlname='CompareGuiPanel']/container[@controlname='_BottomButtonsGroupControl']/element[@controlname='DatasetComparisonGUI.CompareMainPanelDx.CompareButton']/button[@accessiblename='Compare']", 30000, null, "c6310ba6-51f8-4d64-892b-1e0efc2ace60");
            _buttoncancelInfo = new RepoItemInfo(this, "buttonCancel", "/container[@controltypename='DtmUserInterface']/container[@controlname='DatasetComparisonPresentation']/container[@controlname='CompareGuiPanel']/container[@controlname='_BottomButtonsGroupControl']/element[@controlname='DatasetComparisonGUI.CompareMainPanelDx.CancelButton']/button[@accessiblename='Cancel']", 30000, null, "940b0ce4-71c0-4f03-86b7-960ae3b568e2");
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("22ad0338-aa3f-4f98-a85e-7bcb80f52722")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The buttonCompare item.
        /// </summary>
        [RepositoryItem("c6310ba6-51f8-4d64-892b-1e0efc2ace60")]
        public virtual Ranorex.Button buttonCompare
        {
            get
            {
                 return _buttoncompareInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonCompare item info.
        /// </summary>
        [RepositoryItemInfo("c6310ba6-51f8-4d64-892b-1e0efc2ace60")]
        public virtual RepoItemInfo buttonCompareInfo
        {
            get
            {
                return _buttoncompareInfo;
            }
        }

        /// <summary>
        /// The buttonCancel item.
        /// </summary>
        [RepositoryItem("940b0ce4-71c0-4f03-86b7-960ae3b568e2")]
        public virtual Ranorex.Button buttonCancel
        {
            get
            {
                 return _buttoncancelInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonCancel item info.
        /// </summary>
        [RepositoryItemInfo("940b0ce4-71c0-4f03-86b7-960ae3b568e2")]
        public virtual RepoItemInfo buttonCancelInfo
        {
            get
            {
                return _buttoncancelInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    public partial class ActionButtonsFolders
    {
    }
#pragma warning restore 0436
}