///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace EH.PCPS.TestAutomation.CDICommDTMFXA291.V20700.GUI
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the CDICommDTMRepo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    [RepositoryFolder("f5a87b78-57c1-4fe5-86b0-b7cf9c1b47b2")]
    public partial class CDICommDTMRepo : RepoGenBaseFolder
    {
        static CDICommDTMRepo instance = new CDICommDTMRepo();
        CDICommDTMRepoFolders.ApplicationAreaAppFolder _applicationarea;
        CDICommDTMRepoFolders.ComboboxListAppFolder _comboboxlist;

        /// <summary>
        /// Gets the singleton class instance representing the CDICommDTMRepo element repository.
        /// </summary>
        [RepositoryFolder("f5a87b78-57c1-4fe5-86b0-b7cf9c1b47b2")]
        public static CDICommDTMRepo Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public CDICommDTMRepo() 
            : base("CDICommDTMRepo", "/", null, 0, false, "f5a87b78-57c1-4fe5-86b0-b7cf9c1b47b2", ".\\RepositoryImages\\CDICommDTMRepof5a87b78.rximgres")
        {
            _applicationarea = new CDICommDTMRepoFolders.ApplicationAreaAppFolder(this);
            _comboboxlist = new CDICommDTMRepoFolders.ComboboxListAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("f5a87b78-57c1-4fe5-86b0-b7cf9c1b47b2")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationArea folder.
        /// </summary>
        [RepositoryFolder("7c5d13be-24ec-4095-b3e5-0b13bfc2aee2")]
        public virtual CDICommDTMRepoFolders.ApplicationAreaAppFolder ApplicationArea
        {
            get { return _applicationarea; }
        }

        /// <summary>
        /// The ComboboxList folder.
        /// </summary>
        [RepositoryFolder("a826f725-b5fc-4cb3-a1f0-29bb9e3d066b")]
        public virtual CDICommDTMRepoFolders.ComboboxListAppFolder ComboboxList
        {
            get { return _comboboxlist; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    public partial class CDICommDTMRepoFolders
    {
        /// <summary>
        /// The ApplicationAreaAppFolder folder.
        /// </summary>
        [RepositoryFolder("7c5d13be-24ec-4095-b3e5-0b13bfc2aee2")]
        public partial class ApplicationAreaAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _communitcomboboxInfo;
            RepoItemInfo _communitbuttonopenInfo;
            RepoItemInfo _baudratecomboboxInfo;
            RepoItemInfo _baudratebuttonopenInfo;
            RepoItemInfo _buttonrefreshInfo;

            /// <summary>
            /// Creates a new ApplicationArea  folder.
            /// </summary>
            public ApplicationAreaAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationArea", "/element[@childindex='1']/container[@childindex='1']", parentFolder, 30000, null, true, "7c5d13be-24ec-4095-b3e5-0b13bfc2aee2", "")
            {
                _communitcomboboxInfo = new RepoItemInfo(this, "CommUnitCombobox", "element[@childindex='2']/combobox", 30000, null, "71a88c86-f995-4432-8a4d-16b52f6517c7");
                _communitbuttonopenInfo = new RepoItemInfo(this, "CommUnitButtonOpen", "element[@childindex='2']/combobox/button", 30000, null, "f4b77c04-0dc7-43e5-b6bf-0fbc29bf00e4");
                _baudratecomboboxInfo = new RepoItemInfo(this, "BaudRateCombobox", "element[@childindex='6']/combobox", 30000, null, "1746bf67-9d74-4d66-99b1-48ce220d9101");
                _baudratebuttonopenInfo = new RepoItemInfo(this, "BaudRateButtonOpen", "element[@childindex='6']/combobox/button", 30000, null, "b61fe6f1-2b72-448c-b1c0-d877140e4858");
                _buttonrefreshInfo = new RepoItemInfo(this, "ButtonRefresh", "element/button[@accessiblename='Refresh']", 30000, null, "d583202a-0e4b-485d-9d39-c1117aaefad9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7c5d13be-24ec-4095-b3e5-0b13bfc2aee2")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7c5d13be-24ec-4095-b3e5-0b13bfc2aee2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CommUnitCombobox item.
            /// </summary>
            [RepositoryItem("71a88c86-f995-4432-8a4d-16b52f6517c7")]
            public virtual Ranorex.ComboBox CommUnitCombobox
            {
                get
                {
                    return _communitcomboboxInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The CommUnitCombobox item info.
            /// </summary>
            [RepositoryItemInfo("71a88c86-f995-4432-8a4d-16b52f6517c7")]
            public virtual RepoItemInfo CommUnitComboboxInfo
            {
                get
                {
                    return _communitcomboboxInfo;
                }
            }

            /// <summary>
            /// The CommUnitButtonOpen item.
            /// </summary>
            [RepositoryItem("f4b77c04-0dc7-43e5-b6bf-0fbc29bf00e4")]
            public virtual Ranorex.Button CommUnitButtonOpen
            {
                get
                {
                    return _communitbuttonopenInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CommUnitButtonOpen item info.
            /// </summary>
            [RepositoryItemInfo("f4b77c04-0dc7-43e5-b6bf-0fbc29bf00e4")]
            public virtual RepoItemInfo CommUnitButtonOpenInfo
            {
                get
                {
                    return _communitbuttonopenInfo;
                }
            }

            /// <summary>
            /// The BaudRateCombobox item.
            /// </summary>
            [RepositoryItem("1746bf67-9d74-4d66-99b1-48ce220d9101")]
            public virtual Ranorex.ComboBox BaudRateCombobox
            {
                get
                {
                    return _baudratecomboboxInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The BaudRateCombobox item info.
            /// </summary>
            [RepositoryItemInfo("1746bf67-9d74-4d66-99b1-48ce220d9101")]
            public virtual RepoItemInfo BaudRateComboboxInfo
            {
                get
                {
                    return _baudratecomboboxInfo;
                }
            }

            /// <summary>
            /// The BaudRateButtonOpen item.
            /// </summary>
            [RepositoryItem("b61fe6f1-2b72-448c-b1c0-d877140e4858")]
            public virtual Ranorex.Button BaudRateButtonOpen
            {
                get
                {
                    return _baudratebuttonopenInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BaudRateButtonOpen item info.
            /// </summary>
            [RepositoryItemInfo("b61fe6f1-2b72-448c-b1c0-d877140e4858")]
            public virtual RepoItemInfo BaudRateButtonOpenInfo
            {
                get
                {
                    return _baudratebuttonopenInfo;
                }
            }

            /// <summary>
            /// The ButtonRefresh item.
            /// </summary>
            [RepositoryItem("d583202a-0e4b-485d-9d39-c1117aaefad9")]
            public virtual Ranorex.Button ButtonRefresh
            {
                get
                {
                    return _buttonrefreshInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonRefresh item info.
            /// </summary>
            [RepositoryItemInfo("d583202a-0e4b-485d-9d39-c1117aaefad9")]
            public virtual RepoItemInfo ButtonRefreshInfo
            {
                get
                {
                    return _buttonrefreshInfo;
                }
            }
        }

        /// <summary>
        /// The ComboboxListAppFolder folder.
        /// </summary>
        [RepositoryFolder("a826f725-b5fc-4cb3-a1f0-29bb9e3d066b")]
        public partial class ComboboxListAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ComboboxList  folder.
            /// </summary>
            public ComboboxListAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ComboboxList", "/list[@controlid='1000' and @processname='FMPFrame' and @class='ComboLBox']", parentFolder, 30000, null, true, "a826f725-b5fc-4cb3-a1f0-29bb9e3d066b", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a826f725-b5fc-4cb3-a1f0-29bb9e3d066b")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a826f725-b5fc-4cb3-a1f0-29bb9e3d066b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}