///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace EH.PCPS.TestAutomation.NXA_HARTCommDTM.V119580.ChangeDeviceAddress.GUI.ApplicationArea.MainView
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the ChangeDeviceAddressMainViewRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    [RepositoryFolder("9d9bb71b-d7cc-4ee9-ac62-14a12ce61e5d")]
    public partial class ChangeDeviceAddressMainViewRepository : RepoGenBaseFolder
    {
        static ChangeDeviceAddressMainViewRepository instance = new ChangeDeviceAddressMainViewRepository();
        RepoItemInfo _comboboxlistInfo;
        RepoItemInfo _comboboxlistitemInfo;
        RepoItemInfo _changedeviceaddresscomboboxInfo;
        RepoItemInfo _refreshInfo;
        RepoItemInfo _changeInfo;
        RepoItemInfo _treeitemdevicelistInfo;

        /// <summary>
        /// Gets the singleton class instance representing the ChangeDeviceAddressMainViewRepository element repository.
        /// </summary>
        [RepositoryFolder("9d9bb71b-d7cc-4ee9-ac62-14a12ce61e5d")]
        public static ChangeDeviceAddressMainViewRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public ChangeDeviceAddressMainViewRepository() 
            : base("ChangeDeviceAddressMainViewRepository", "/", null, 0, false, "9d9bb71b-d7cc-4ee9-ac62-14a12ce61e5d", ".\\RepositoryImages\\ChangeDeviceAddressMainViewRepository9d9bb71b.rximgres")
        {
            _comboboxlistInfo = new RepoItemInfo(this, "comboBoxList", "/form/element/list", 30000, null, "8758146b-1ba7-4971-913a-71ac98f572aa");
            _comboboxlistitemInfo = new RepoItemInfo(this, "comboBoxListItem", "/form/element/list/listitem", 30000, null, "148d0623-a03e-4771-be0d-d9fee8496f67");
            _changedeviceaddresscomboboxInfo = new RepoItemInfo(this, "ChangeDeviceAddressComboBox", "/?/form/?/?/container[@controlname='GUITransparentProxy']/?/?/element[@controlname='changeDeviceAddressComboBox']", 30000, null, "60943304-9219-48f6-b51c-335e3932a461");
            _refreshInfo = new RepoItemInfo(this, "Refresh", "/?/form//container[@controlname='ContainerForm']/element[@controlname='refreshButton']/button[@accessiblename='Refresh']", 30000, null, "36fb0533-39b8-4c57-a30a-2f36c430a360");
            _changeInfo = new RepoItemInfo(this, "Change", "/?/form//container[@controlname='ContainerForm']/element[@controlname='changeButton']/button[@accessiblename='Change']", 30000, null, "45dc6141-8325-428f-8fff-6919640f66ee");
            _treeitemdevicelistInfo = new RepoItemInfo(this, "treeItemDeviceList", "/?/form/?/?/container[@controlname='GUITransparentProxy']/?/?/element[@controlname='deviceListControl']/tree[@accessiblename='deviceListControl']/container[2]/treeitem", 30000, null, "bb76d82e-2fca-452d-bdbc-260b56468256");
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("9d9bb71b-d7cc-4ee9-ac62-14a12ce61e5d")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The comboBoxList item.
        /// </summary>
        [RepositoryItem("8758146b-1ba7-4971-913a-71ac98f572aa")]
        public virtual Ranorex.List comboBoxList
        {
            get
            {
                 return _comboboxlistInfo.CreateAdapter<Ranorex.List>(true);
            }
        }

        /// <summary>
        /// The comboBoxList item info.
        /// </summary>
        [RepositoryItemInfo("8758146b-1ba7-4971-913a-71ac98f572aa")]
        public virtual RepoItemInfo comboBoxListInfo
        {
            get
            {
                return _comboboxlistInfo;
            }
        }

        /// <summary>
        /// The comboBoxListItem item.
        /// </summary>
        [RepositoryItem("148d0623-a03e-4771-be0d-d9fee8496f67")]
        public virtual Ranorex.ListItem comboBoxListItem
        {
            get
            {
                 return _comboboxlistitemInfo.CreateAdapter<Ranorex.ListItem>(true);
            }
        }

        /// <summary>
        /// The comboBoxListItem item info.
        /// </summary>
        [RepositoryItemInfo("148d0623-a03e-4771-be0d-d9fee8496f67")]
        public virtual RepoItemInfo comboBoxListItemInfo
        {
            get
            {
                return _comboboxlistitemInfo;
            }
        }

        /// <summary>
        /// The ChangeDeviceAddressComboBox item.
        /// </summary>
        [RepositoryItem("60943304-9219-48f6-b51c-335e3932a461")]
        public virtual Ranorex.Unknown ChangeDeviceAddressComboBox
        {
            get
            {
                 return _changedeviceaddresscomboboxInfo.CreateAdapter<Ranorex.Unknown>(true);
            }
        }

        /// <summary>
        /// The ChangeDeviceAddressComboBox item info.
        /// </summary>
        [RepositoryItemInfo("60943304-9219-48f6-b51c-335e3932a461")]
        public virtual RepoItemInfo ChangeDeviceAddressComboBoxInfo
        {
            get
            {
                return _changedeviceaddresscomboboxInfo;
            }
        }

        /// <summary>
        /// The Refresh item.
        /// </summary>
        [RepositoryItem("36fb0533-39b8-4c57-a30a-2f36c430a360")]
        public virtual Ranorex.Button Refresh
        {
            get
            {
                 return _refreshInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The Refresh item info.
        /// </summary>
        [RepositoryItemInfo("36fb0533-39b8-4c57-a30a-2f36c430a360")]
        public virtual RepoItemInfo RefreshInfo
        {
            get
            {
                return _refreshInfo;
            }
        }

        /// <summary>
        /// The Change item.
        /// </summary>
        [RepositoryItem("45dc6141-8325-428f-8fff-6919640f66ee")]
        public virtual Ranorex.Button Change
        {
            get
            {
                 return _changeInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The Change item info.
        /// </summary>
        [RepositoryItemInfo("45dc6141-8325-428f-8fff-6919640f66ee")]
        public virtual RepoItemInfo ChangeInfo
        {
            get
            {
                return _changeInfo;
            }
        }

        /// <summary>
        /// The treeItemDeviceList item.
        /// </summary>
        [RepositoryItem("bb76d82e-2fca-452d-bdbc-260b56468256")]
        public virtual Ranorex.TreeItem treeItemDeviceList
        {
            get
            {
                 return _treeitemdevicelistInfo.CreateAdapter<Ranorex.TreeItem>(true);
            }
        }

        /// <summary>
        /// The treeItemDeviceList item info.
        /// </summary>
        [RepositoryItemInfo("bb76d82e-2fca-452d-bdbc-260b56468256")]
        public virtual RepoItemInfo treeItemDeviceListInfo
        {
            get
            {
                return _treeitemdevicelistInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    public partial class ChangeDeviceAddressMainViewRepositoryFolders
    {
    }
#pragma warning restore 0436
}