//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EH.PCPS.TestAutomation.DeviceCare.CI.GUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringTranslation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringTranslation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EH.PCPS.TestAutomation.DeviceCare.CI.GUI.StringTranslation", typeof(StringTranslation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_ successful.
        /// </summary>
        internal static string English_download_successful {
            get {
                return ResourceManager.GetString("English_download_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload_ successful.
        /// </summary>
        internal static string English_upload_successful {
            get {
                return ResourceManager.GetString("English_upload_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to téléchargement_réussi.
        /// </summary>
        internal static string French_download_successful {
            get {
                return ResourceManager.GetString("French_download_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to téléchargement_réussi.
        /// </summary>
        internal static string French_upload_successful {
            get {
                return ResourceManager.GetString("French_upload_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_erfolgreich.
        /// </summary>
        internal static string German_download_successful {
            get {
                return ResourceManager.GetString("German_download_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hochladen_erfolgreich.
        /// </summary>
        internal static string German_upload_successful {
            get {
                return ResourceManager.GetString("German_upload_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_completato.
        /// </summary>
        internal static string Italian_download_successful {
            get {
                return ResourceManager.GetString("Italian_download_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to caricamento_completato.
        /// </summary>
        internal static string Italian_upload_successful {
            get {
                return ResourceManager.GetString("Italian_upload_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to descarga_satisfactoriamente.
        /// </summary>
        internal static string Spanish_download_successful {
            get {
                return ResourceManager.GetString("Spanish_download_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carga_satisfactoriamente.
        /// </summary>
        internal static string Spanish_upload_successful {
            get {
                return ResourceManager.GetString("Spanish_upload_successful", resourceCulture);
            }
        }
    }
}
