///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace EH.PCPS.TestAutomation.DeviceCare.V10300.Functions.MenuArea.MainMenu.Execution
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CloseDeviceCare recording.
    /// </summary>
    [TestModule("95739d21-a4be-4d2f-875f-26949ca55924", ModuleType.Recording, 1)]
    public partial class CloseDeviceCare : ITestModule
    {
        /// <summary>
        /// Holds an instance of the EH.PCPS.TestAutomation.DeviceCare.V10300.GUI.DeviceCareApplication repository.
        /// </summary>
        public static EH.PCPS.TestAutomation.DeviceCare.V10300.GUI.DeviceCareApplication repo = EH.PCPS.TestAutomation.DeviceCare.V10300.GUI.DeviceCareApplication.Instance;

        static CloseDeviceCare instance = new CloseDeviceCare();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CloseDeviceCare()
        {
            TimeOutInMilliseconds = "60000";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CloseDeviceCare Instance
        {
            get { return instance; }
        }

#region Variables

        string _TimeOutInMilliseconds;

        /// <summary>
        /// Gets or sets the value of variable TimeOutInMilliseconds.
        /// </summary>
        [TestVariable("41da8166-7bbc-4bac-b882-e1254d7fffb9")]
        public string TimeOutInMilliseconds
        {
            get { return _TimeOutInMilliseconds; }
            set { _TimeOutInMilliseconds = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MenuArea.MainMenu.MainMenuItems.ButtonExit' at Center.", repo.MenuArea.MainMenu.MainMenuItems.ButtonExitInfo, new RecordItemIndex(0));
            repo.MenuArea.MainMenu.MainMenuItems.ButtonExit.Click();
            Delay.Milliseconds(200);
            
            WaitForNotExists();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
