///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace EH.PCPS.TestAutomation.DeviceCare.V10300.Functions.ApplicationArea.Page_Help.Validation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CheckConnection recording.
    /// </summary>
    [TestModule("f359d49e-5257-43c3-9a4b-d1c95a02a2a0", ModuleType.Recording, 1)]
    public partial class CheckConnection : ITestModule
    {
        /// <summary>
        /// Holds an instance of the EH.PCPS.TestAutomation.DeviceCare.V10300.GUI.DeviceCareApplication repository.
        /// </summary>
        public static EH.PCPS.TestAutomation.DeviceCare.V10300.GUI.DeviceCareApplication repo = EH.PCPS.TestAutomation.DeviceCare.V10300.GUI.DeviceCareApplication.Instance;

        static CheckConnection instance = new CheckConnection();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CheckConnection()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CheckConnection Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'DeviceCare.ApplicationArea.Page_Help.Connection'.", repo.DeviceCare.ApplicationArea.Page_Help.Connection.SelfInfo, new RecordItemIndex(0));
            Validate.Attribute(repo.DeviceCare.ApplicationArea.Page_Help.Connection.SelfInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'DeviceCare.ApplicationArea.Page_Help.Connection.Button_ConnectionAssistant'.", repo.DeviceCare.ApplicationArea.Page_Help.Connection.Button_ConnectionAssistantInfo, new RecordItemIndex(1));
            Validate.Attribute(repo.DeviceCare.ApplicationArea.Page_Help.Connection.Button_ConnectionAssistantInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'DeviceCare.ApplicationArea.Page_Help.Connection.Button_ConnectionAssistant'.", repo.DeviceCare.ApplicationArea.Page_Help.Connection.Button_ConnectionAssistantInfo, new RecordItemIndex(2));
            Validate.Attribute(repo.DeviceCare.ApplicationArea.Page_Help.Connection.Button_ConnectionAssistantInfo, "Enabled", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'DeviceCare.ApplicationArea.Page_Help.Connection.Text_Title_ConnectionAssistant'.", repo.DeviceCare.ApplicationArea.Page_Help.Connection.Text_Title_ConnectionAssistantInfo, new RecordItemIndex(3));
            Validate.Attribute(repo.DeviceCare.ApplicationArea.Page_Help.Connection.Text_Title_ConnectionAssistantInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'DeviceCare.ApplicationArea.Page_Help.Connection.Text_SubTitle_ConnectionAssistant'.", repo.DeviceCare.ApplicationArea.Page_Help.Connection.Text_SubTitle_ConnectionAssistantInfo, new RecordItemIndex(4));
            Validate.Attribute(repo.DeviceCare.ApplicationArea.Page_Help.Connection.Text_SubTitle_ConnectionAssistantInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'DeviceCare.ApplicationArea.Page_Help.Connection.Button_HART'.", repo.DeviceCare.ApplicationArea.Page_Help.Connection.Button_HARTInfo, new RecordItemIndex(5));
            Validate.Attribute(repo.DeviceCare.ApplicationArea.Page_Help.Connection.Button_HARTInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'DeviceCare.ApplicationArea.Page_Help.Connection.Button_HART'.", repo.DeviceCare.ApplicationArea.Page_Help.Connection.Button_HARTInfo, new RecordItemIndex(6));
            Validate.Attribute(repo.DeviceCare.ApplicationArea.Page_Help.Connection.Button_HARTInfo, "Enabled", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'DeviceCare.ApplicationArea.Page_Help.Connection.Text_Title_HART'.", repo.DeviceCare.ApplicationArea.Page_Help.Connection.Text_Title_HARTInfo, new RecordItemIndex(7));
            Validate.Attribute(repo.DeviceCare.ApplicationArea.Page_Help.Connection.Text_Title_HARTInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'DeviceCare.ApplicationArea.Page_Help.Connection.Text_SubTitle_HART'.", repo.DeviceCare.ApplicationArea.Page_Help.Connection.Text_SubTitle_HARTInfo, new RecordItemIndex(8));
            Validate.Attribute(repo.DeviceCare.ApplicationArea.Page_Help.Connection.Text_SubTitle_HARTInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'DeviceCare.ApplicationArea.Page_Help.Connection.Button_Profibus'.", repo.DeviceCare.ApplicationArea.Page_Help.Connection.Button_ProfibusInfo, new RecordItemIndex(9));
            Validate.Attribute(repo.DeviceCare.ApplicationArea.Page_Help.Connection.Button_ProfibusInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'DeviceCare.ApplicationArea.Page_Help.Connection.Button_Profibus'.", repo.DeviceCare.ApplicationArea.Page_Help.Connection.Button_ProfibusInfo, new RecordItemIndex(10));
            Validate.Attribute(repo.DeviceCare.ApplicationArea.Page_Help.Connection.Button_ProfibusInfo, "Enabled", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'DeviceCare.ApplicationArea.Page_Help.Connection.Text_Title_PROFIBUS'.", repo.DeviceCare.ApplicationArea.Page_Help.Connection.Text_Title_PROFIBUSInfo, new RecordItemIndex(11));
            Validate.Attribute(repo.DeviceCare.ApplicationArea.Page_Help.Connection.Text_Title_PROFIBUSInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'DeviceCare.ApplicationArea.Page_Help.Connection.Text_SubTitle_PROFIBUS'.", repo.DeviceCare.ApplicationArea.Page_Help.Connection.Text_SubTitle_PROFIBUSInfo, new RecordItemIndex(12));
            Validate.Attribute(repo.DeviceCare.ApplicationArea.Page_Help.Connection.Text_SubTitle_PROFIBUSInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'DeviceCare.ApplicationArea.Page_Help.Connection.Button_FoundationFieldbus'.", repo.DeviceCare.ApplicationArea.Page_Help.Connection.Button_FoundationFieldbusInfo, new RecordItemIndex(13));
            Validate.Attribute(repo.DeviceCare.ApplicationArea.Page_Help.Connection.Button_FoundationFieldbusInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'DeviceCare.ApplicationArea.Page_Help.Connection.Button_FoundationFieldbus'.", repo.DeviceCare.ApplicationArea.Page_Help.Connection.Button_FoundationFieldbusInfo, new RecordItemIndex(14));
            Validate.Attribute(repo.DeviceCare.ApplicationArea.Page_Help.Connection.Button_FoundationFieldbusInfo, "Enabled", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'DeviceCare.ApplicationArea.Page_Help.Connection.Text_Title_FoundationFieldbus'.", repo.DeviceCare.ApplicationArea.Page_Help.Connection.Text_Title_FoundationFieldbusInfo, new RecordItemIndex(15));
            Validate.Attribute(repo.DeviceCare.ApplicationArea.Page_Help.Connection.Text_Title_FoundationFieldbusInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'DeviceCare.ApplicationArea.Page_Help.Connection.Text_SubTitle_FoundationFieldbus'.", repo.DeviceCare.ApplicationArea.Page_Help.Connection.Text_SubTitle_FoundationFieldbusInfo, new RecordItemIndex(16));
            Validate.Attribute(repo.DeviceCare.ApplicationArea.Page_Help.Connection.Text_SubTitle_FoundationFieldbusInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'DeviceCare.ApplicationArea.Page_Help.Connection.Button_CDI'.", repo.DeviceCare.ApplicationArea.Page_Help.Connection.Button_CDIInfo, new RecordItemIndex(17));
            Validate.Attribute(repo.DeviceCare.ApplicationArea.Page_Help.Connection.Button_CDIInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'DeviceCare.ApplicationArea.Page_Help.Connection.Button_CDI'.", repo.DeviceCare.ApplicationArea.Page_Help.Connection.Button_CDIInfo, new RecordItemIndex(18));
            Validate.Attribute(repo.DeviceCare.ApplicationArea.Page_Help.Connection.Button_CDIInfo, "Enabled", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'DeviceCare.ApplicationArea.Page_Help.Connection.Text_Title_CDI'.", repo.DeviceCare.ApplicationArea.Page_Help.Connection.Text_Title_CDIInfo, new RecordItemIndex(19));
            Validate.Attribute(repo.DeviceCare.ApplicationArea.Page_Help.Connection.Text_Title_CDIInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'DeviceCare.ApplicationArea.Page_Help.Connection.Text_SubTitle_CDI'.", repo.DeviceCare.ApplicationArea.Page_Help.Connection.Text_SubTitle_CDIInfo, new RecordItemIndex(20));
            Validate.Attribute(repo.DeviceCare.ApplicationArea.Page_Help.Connection.Text_SubTitle_CDIInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'DeviceCare.ApplicationArea.Page_Help.Connection.Button_EHInterfaces'.", repo.DeviceCare.ApplicationArea.Page_Help.Connection.Button_EHInterfacesInfo, new RecordItemIndex(21));
            Validate.Attribute(repo.DeviceCare.ApplicationArea.Page_Help.Connection.Button_EHInterfacesInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'DeviceCare.ApplicationArea.Page_Help.Connection.Button_EHInterfaces'.", repo.DeviceCare.ApplicationArea.Page_Help.Connection.Button_EHInterfacesInfo, new RecordItemIndex(22));
            Validate.Attribute(repo.DeviceCare.ApplicationArea.Page_Help.Connection.Button_EHInterfacesInfo, "Enabled", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'DeviceCare.ApplicationArea.Page_Help.Connection.Text_Title_EHInterfaces'.", repo.DeviceCare.ApplicationArea.Page_Help.Connection.Text_Title_EHInterfacesInfo, new RecordItemIndex(23));
            Validate.Attribute(repo.DeviceCare.ApplicationArea.Page_Help.Connection.Text_Title_EHInterfacesInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'DeviceCare.ApplicationArea.Page_Help.Connection.Text_SubTitle_EHInterfaces'.", repo.DeviceCare.ApplicationArea.Page_Help.Connection.Text_SubTitle_EHInterfacesInfo, new RecordItemIndex(24));
            Validate.Attribute(repo.DeviceCare.ApplicationArea.Page_Help.Connection.Text_SubTitle_EHInterfacesInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
