///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace EH.PCPS.TestAutomation.DeviceCare.V10300.Functions.ApplicationArea.Page_Help.Validation
{
	public partial class CheckAbout
	{
		/// <summary>
		/// This method gets called right after the recording has been started.
		/// It can be used to execute recording specific initialization code.
		/// </summary>
		private void Init()
		{
			// Your recording specific initialization code goes here.
			string[] versionNumberPart = VersionUnderTest.Split('.');
			VersionUnderTest = "";
			for (int i=0; i<versionNumberPart.Length; i++)
			{
				if (versionNumberPart[i].StartsWith("0"))
				{
					versionNumberPart[i] = versionNumberPart[i].Substring(1);
				}
				
				VersionUnderTest += versionNumberPart[i];
				
				if (i != versionNumberPart.Length -1)
				{
					VersionUnderTest += ".";
				}
			}
		}

        /// <summary>
        /// 
        /// </summary>
        public void Validate_Text_SubTitle_Version()
        {
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text=$VersionUnderTest) on item 'DeviceCare.ApplicationArea.Page_Help.About.Text_SubTitle_Version'.", repo.DeviceCare.ApplicationArea.Page_Help.About.Text_SubTitle_VersionInfo);
            Validate.Attribute(repo.DeviceCare.ApplicationArea.Page_Help.About.Text_SubTitle_VersionInfo, "Text", VersionUnderTest);
        }

	}
}