///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace EH.PCPS.TestAutomation.TestPackageUpdateA2016.SaveRestore.GUI.ApplicationArea.MainView
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Selection element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    [RepositoryFolder("75c8ea02-a7b9-4539-9341-c3d492f7f580")]
    public partial class Selection : RepoGenBaseFolder
    {
        static Selection instance = new Selection();
        RepoItemInfo _checkboxdownloadInfo;
        RepoItemInfo _checkboxuploadInfo;
        RepoItemInfo _buttonrestorefromInfo;
        RepoItemInfo _buttonsaveasInfo;
        RepoItemInfo _txtstatusofdeviceInfo;
        RepoItemInfo _txtstatusofsaverestoreassistentInfo;
        RepoItemInfo _radiobuttondownloadmodeduplicateInfo;
        RepoItemInfo _radiobuttondownloadmodeallparameterInfo;

        /// <summary>
        /// Gets the singleton class instance representing the Selection element repository.
        /// </summary>
        [RepositoryFolder("75c8ea02-a7b9-4539-9341-c3d492f7f580")]
        public static Selection Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Selection() 
            : base("Selection", "/", null, 0, false, "75c8ea02-a7b9-4539-9341-c3d492f7f580", ".\\RepositoryImages\\Selection75c8ea02.rximgres")
        {
            _checkboxdownloadInfo = new RepoItemInfo(this, "checkboxDownload", "/container[@controltypename='DtmUserInterface']/container[@controlname='SaveRestoreControl']/container[@controlname='RestorePage']/?/?/container[@controlname='RestorePanel']/checkbox[@controlname='checkBoxDownload']", 30000, null, "b145200a-bfdc-4044-b3ad-3253f74d95c3");
            _checkboxuploadInfo = new RepoItemInfo(this, "checkboxUpload", "/container[@controltypename='DtmUserInterface']/container[@controlname='SaveRestoreControl']/container[@controlname='RestorePage']/?/?/container[@controlname='SavePanel']/checkbox[@controlname='checkBoxUpload']", 30000, null, "63c9ae6f-5f16-4aab-9f31-672ec3af59ca");
            _buttonrestorefromInfo = new RepoItemInfo(this, "buttonRestoreFrom", "/container[@controltypename='DtmUserInterface']/container[@controlname='SaveRestoreControl']/container[@controlname='RestorePage']/container[@controlname='groupControlMain']/?/?/button[@accessiblename='Restore from...']", 30000, null, "63409d35-ff85-497b-89b8-05e3eb0d1534");
            _buttonsaveasInfo = new RepoItemInfo(this, "buttonSaveAs", "/container[@controltypename='DtmUserInterface']/container[@controlname='SaveRestoreControl']/container[@controlname='RestorePage']/container[@controlname='groupControlMain']/?/?/button[@accessiblename='Save as...']", 30000, null, "6c2ab80e-5d19-44d5-a029-d08e808edfe9");
            _txtstatusofdeviceInfo = new RepoItemInfo(this, "txtStatusOfDevice", "/container[@controltypename='DtmUserInterface']/container[@controlname='SaveRestoreControl']/container[@controlname='RestorePage']/container[@controlname='groupControlMain']/container[@controlname='groupControlDeviceStatus']/?/?/text", 30000, null, "6a7a3dea-2cf9-4966-96e1-1a829603746c");
            _txtstatusofsaverestoreassistentInfo = new RepoItemInfo(this, "txtStatusOfSaveRestoreAssistent", "/container[@controltypename='DtmUserInterface']/container[@controlname='SaveRestoreControl']/container[@controlname='RestorePage']/container[@controlname='groupControlMain']/container[@controlname='groupControl1']/?/?/text", 30000, null, "d5e79da2-1a50-46f5-beeb-a70b7368d0fe");
            _radiobuttondownloadmodeduplicateInfo = new RepoItemInfo(this, "radioButtonDownloadModeDuplicate", "/container[@controltypename='DtmUserInterface']/container[@controlname='SaveRestoreControl']/?/?/container[@controlname='groupControlMain']/container[@controlname='RestorePanel']/container[@controlname='groupControlDownloadMode']/radiobutton[@controlname='radioButtonDuplicate']", 30000, null, "c9a65bf8-6b0d-4242-a454-d3a8feafd252");
            _radiobuttondownloadmodeallparameterInfo = new RepoItemInfo(this, "radioButtonDownloadModeAllParameter", "/container[@controltypename='DtmUserInterface']/container[@controlname='SaveRestoreControl']/?/?/container[@controlname='groupControlMain']/container[@controlname='RestorePanel']/container[@controlname='groupControlDownloadMode']/radiobutton[@controlname='radioButtonRestore']", 30000, null, "c0503331-e7a8-40fb-8abe-3e3e11004a0e");
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("75c8ea02-a7b9-4539-9341-c3d492f7f580")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The checkboxDownload item.
        /// </summary>
        [RepositoryItem("b145200a-bfdc-4044-b3ad-3253f74d95c3")]
        public virtual Ranorex.CheckBox checkboxDownload
        {
            get
            {
                 return _checkboxdownloadInfo.CreateAdapter<Ranorex.CheckBox>(true);
            }
        }

        /// <summary>
        /// The checkboxDownload item info.
        /// </summary>
        [RepositoryItemInfo("b145200a-bfdc-4044-b3ad-3253f74d95c3")]
        public virtual RepoItemInfo checkboxDownloadInfo
        {
            get
            {
                return _checkboxdownloadInfo;
            }
        }

        /// <summary>
        /// The checkboxUpload item.
        /// </summary>
        [RepositoryItem("63c9ae6f-5f16-4aab-9f31-672ec3af59ca")]
        public virtual Ranorex.CheckBox checkboxUpload
        {
            get
            {
                 return _checkboxuploadInfo.CreateAdapter<Ranorex.CheckBox>(true);
            }
        }

        /// <summary>
        /// The checkboxUpload item info.
        /// </summary>
        [RepositoryItemInfo("63c9ae6f-5f16-4aab-9f31-672ec3af59ca")]
        public virtual RepoItemInfo checkboxUploadInfo
        {
            get
            {
                return _checkboxuploadInfo;
            }
        }

        /// <summary>
        /// The buttonRestoreFrom item.
        /// </summary>
        [RepositoryItem("63409d35-ff85-497b-89b8-05e3eb0d1534")]
        public virtual Ranorex.Button buttonRestoreFrom
        {
            get
            {
                 return _buttonrestorefromInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonRestoreFrom item info.
        /// </summary>
        [RepositoryItemInfo("63409d35-ff85-497b-89b8-05e3eb0d1534")]
        public virtual RepoItemInfo buttonRestoreFromInfo
        {
            get
            {
                return _buttonrestorefromInfo;
            }
        }

        /// <summary>
        /// The buttonSaveAs item.
        /// </summary>
        [RepositoryItem("6c2ab80e-5d19-44d5-a029-d08e808edfe9")]
        public virtual Ranorex.Button buttonSaveAs
        {
            get
            {
                 return _buttonsaveasInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The buttonSaveAs item info.
        /// </summary>
        [RepositoryItemInfo("6c2ab80e-5d19-44d5-a029-d08e808edfe9")]
        public virtual RepoItemInfo buttonSaveAsInfo
        {
            get
            {
                return _buttonsaveasInfo;
            }
        }

        /// <summary>
        /// The txtStatusOfDevice item.
        /// </summary>
        [RepositoryItem("6a7a3dea-2cf9-4966-96e1-1a829603746c")]
        public virtual Ranorex.Text txtStatusOfDevice
        {
            get
            {
                 return _txtstatusofdeviceInfo.CreateAdapter<Ranorex.Text>(true);
            }
        }

        /// <summary>
        /// The txtStatusOfDevice item info.
        /// </summary>
        [RepositoryItemInfo("6a7a3dea-2cf9-4966-96e1-1a829603746c")]
        public virtual RepoItemInfo txtStatusOfDeviceInfo
        {
            get
            {
                return _txtstatusofdeviceInfo;
            }
        }

        /// <summary>
        /// The txtStatusOfSaveRestoreAssistent item.
        /// </summary>
        [RepositoryItem("d5e79da2-1a50-46f5-beeb-a70b7368d0fe")]
        public virtual Ranorex.Text txtStatusOfSaveRestoreAssistent
        {
            get
            {
                 return _txtstatusofsaverestoreassistentInfo.CreateAdapter<Ranorex.Text>(true);
            }
        }

        /// <summary>
        /// The txtStatusOfSaveRestoreAssistent item info.
        /// </summary>
        [RepositoryItemInfo("d5e79da2-1a50-46f5-beeb-a70b7368d0fe")]
        public virtual RepoItemInfo txtStatusOfSaveRestoreAssistentInfo
        {
            get
            {
                return _txtstatusofsaverestoreassistentInfo;
            }
        }

        /// <summary>
        /// The radioButtonDownloadModeDuplicate item.
        /// </summary>
        [RepositoryItem("c9a65bf8-6b0d-4242-a454-d3a8feafd252")]
        public virtual Ranorex.RadioButton radioButtonDownloadModeDuplicate
        {
            get
            {
                 return _radiobuttondownloadmodeduplicateInfo.CreateAdapter<Ranorex.RadioButton>(true);
            }
        }

        /// <summary>
        /// The radioButtonDownloadModeDuplicate item info.
        /// </summary>
        [RepositoryItemInfo("c9a65bf8-6b0d-4242-a454-d3a8feafd252")]
        public virtual RepoItemInfo radioButtonDownloadModeDuplicateInfo
        {
            get
            {
                return _radiobuttondownloadmodeduplicateInfo;
            }
        }

        /// <summary>
        /// The radioButtonDownloadModeAllParameter item.
        /// </summary>
        [RepositoryItem("c0503331-e7a8-40fb-8abe-3e3e11004a0e")]
        public virtual Ranorex.RadioButton radioButtonDownloadModeAllParameter
        {
            get
            {
                 return _radiobuttondownloadmodeallparameterInfo.CreateAdapter<Ranorex.RadioButton>(true);
            }
        }

        /// <summary>
        /// The radioButtonDownloadModeAllParameter item info.
        /// </summary>
        [RepositoryItemInfo("c0503331-e7a8-40fb-8abe-3e3e11004a0e")]
        public virtual RepoItemInfo radioButtonDownloadModeAllParameterInfo
        {
            get
            {
                return _radiobuttondownloadmodeallparameterInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    public partial class SelectionFolders
    {
    }
#pragma warning restore 0436
}